In [17]:
import dspy
import dspy.evaluate
import mlflow
import pandas as pd
from dotenv import find_dotenv, load_dotenv
from dspy import LM, Evaluate, Example, MIPROv2, ReAct

In [2]:
_ = load_dotenv(find_dotenv("../creds/.env"), verbose=True)

In [3]:
mlflow.set_experiment("dspy/03")
mlflow.dspy.autolog(
    log_evals=True,
    log_compiles=True,
    log_traces_from_compile=True,
)

2025/07/23 15:58:54 INFO mlflow.tracking.fluent: Experiment with name 'dspy/03' does not exist. Creating a new experiment.

In [5]:
def search_wikipedia(query: str) -> list[str]:
    results = dspy.ColBERTv2(url="http://20.102.90.50:2017/wiki17_abstracts")(query, k=3)

    return [x["text"] for x in results]

In [7]:
def create_question_example(row: pd.Series) -> Example:
    return Example(question=row["question"], answer=row["answer"]).with_inputs("question")

In [8]:
trainset_df = pd.read_json("../data/trainset.jsonl.gz", lines=True)
valset_df = pd.read_json("../data/valset.jsonl.gz", lines=True)

In [9]:
trainset = trainset_df.apply(create_question_example, axis=1).values.tolist()
valset = valset_df.apply(create_question_example, axis=1).values.tolist()

### qwen3:1.7b

In [4]:
lm = LM(
    "ollama_chat/qwen3:1.7b",
    api_base="http://localhost:11434",
    api_key="",
    max_tokens=40960,
    temperature=0.0,
    cache=False,
)
dspy.configure(lm=lm)

In [6]:
react = ReAct("question -> answer", tools=[search_wikipedia])

In [10]:
tp = MIPROv2(
    metric=dspy.evaluate.answer_exact_match,
    auto="light",
    num_threads=8,
)

In [11]:
# dspy.cache.load_memory_cache("../temp/memory_cache.pkl")

In [12]:
optimized_react = tp.compile(
    react,
    trainset=trainset[:10],
    valset=valset[:10],
    requires_permission_to_run=False,
)

2025/07/23 15:58:55 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'fe92b8138624478298b3dbcbd1d61b79', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current dspy workflow
2025/07/23 15:58:55 INFO dspy.teleprompt.mipro_optimizer_v2:
RUNNING WITH THE FOLLOWING LIGHT AUTO RUN SETTINGS:
num_trials: 20
minibatch: False
num_fewshot_candidates: 6
num_instruct_candidates: 3
valset size: 10

2025/07/23 15:58:55 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 1: BOOTSTRAP FEWSHOT EXAMPLES <==
2025/07/23 15:58:55 INFO dspy.teleprompt.mipro_optimizer_v2: These will be used as few-shot example candidates for our program and for creating instructions.

2025/07/23 15:58:55 INFO dspy.teleprompt.mipro_optimizer_v2: Bootstrapping N=6 sets of demonstrations...

Bootstrapping set 1/6
Bootstrapping set 2/6
Bootstrapping set 3/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

100%|██████████| 10/10 [01:50<00:00, 11.09s/it]

Bootstrapped 1 full traces after 9 examples for up to 1 rounds, amounting to 10 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 4/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

100%|██████████| 10/10 [01:46<00:00, 10.67s/it]

Bootstrapped 1 full traces after 9 examples for up to 1 rounds, amounting to 10 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 5/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

 30%|███       | 3/10 [00:28<01:07,  9.64s/it]

Bootstrapped 1 full traces after 3 examples for up to 1 rounds, amounting to 3 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 6/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

100%|██████████| 10/10 [01:53<00:00, 11.36s/it]

Bootstrapped 1 full traces after 9 examples for up to 1 rounds, amounting to 10 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

2025/07/23 16:04:59 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 2: PROPOSE INSTRUCTION CANDIDATES <==
2025/07/23 16:04:59 INFO dspy.teleprompt.mipro_optimizer_v2: We will use the few-shot examples from the previous step, a generated dataset summary, a summary of the program code, and a randomly selected prompting tip to propose instructions.
2025/07/23 16:05:09 INFO dspy.teleprompt.mipro_optimizer_v2:
Proposing N=3 instructions...

2025/07/23 16:06:28 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 0:

2025/07/23 16:06:28 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the fields `question`, produce the fields `answer`.

You are an Agent. In each episode, you will be given the fields `question` as input. And you can see your past trajectory so far.
Your goal is to use one or more of the supplied tools to collect any necessary information for producing `answer`.

To do this, you will interleave next_thought, next_tool_name, and next_tool_args in each turn, and also when finishing the task.
After each tool call, you receive a resulting observation, which gets appended to your trajectory.

When writing next_thought, you may reason about the current situation and plan for future steps.
When selecting the next_tool_name and its next_tool_args, the tool must be one of:

(1) search_wikipedia. It takes arguments {'query': {'type': 'string'}}.
(2) finish, whose description is <desc>Marks the task as complete. That is, signals that all information for producing the outputs, i.e. `answer`, are now available to be extracted.</desc>. It takes arguments {}.
When providing `next_tool_args`, the value inside the field must be in JSON format

2025/07/23 16:06:28 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Who did Holly Dunn record "Daddy's Hands" for?
Trajectory: [[ ## thought_0 ## ]]
I need to search Wikipedia for the information about who Holly Dunn recorded "Daddy's Hands" for.

2025/07/23 16:06:28 INFO dspy.teleprompt.mipro_optimizer_v2: 2: MTM Records

2025/07/23 16:06:28 INFO dspy.teleprompt.mipro_optimizer_v2:

2025/07/23 16:06:28 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 1:

2025/07/23 16:06:28 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the fields `question`, produce the fields `answer`.

2025/07/23 16:06:28 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Given the provided observations, determine the record label for which Holly Dunn recorded the song "Daddy's Hands." Analyze the data from the Wikipedia search results to extract the specific recording label.[[ ## completed ## ]]

2025/07/23 16:06:28 INFO dspy.teleprompt.mipro_optimizer_v2: 2: Given the fields `question`, produce the fields `answer`.

2025/07/23 16:06:28 INFO dspy.teleprompt.mipro_optimizer_v2:

2025/07/23 16:06:29 INFO dspy.teleprompt.mipro_optimizer_v2: ==> STEP 3: FINDING OPTIMAL PROMPT PARAMETERS <==
2025/07/23 16:06:29 INFO dspy.teleprompt.mipro_optimizer_v2: We will evaluate the program over a series of trials with different combinations of instructions and few-shot examples to find the optimal combination using Bayesian Optimization.

2025/07/23 16:06:29 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 1 / 20 - Full Evaluation of Default Program ==

Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [01:22<00:00,  8.24s/it]

2025/07/23 16:07:51 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/23 16:07:51 INFO dspy.teleprompt.mipro_optimizer_v2: Default program score: 30.0

/home/eugene/projects/deeplearning.ai/.venv/lib/python3.13/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
2025/07/23 16:07:51 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 2 / 20 =====

🏃 View run eval_full_0 at: http://localhost:5000/#/experiments/1/runs/26660900bc2d498ba05dc64863fca897
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [01:18<00:00,  7.87s/it]

2025/07/23 16:09:10 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/23 16:09:10 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 3', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 0'].
2025/07/23 16:09:10 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0]
2025/07/23 16:09:10 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 30.0
2025/07/23 16:09:10 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/23 16:09:10 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 3 / 20 =====

🏃 View run eval_full_1 at: http://localhost:5000/#/experiments/1/runs/e6d73132b11e4e38ab7c1a99cf22f70a
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [01:24<00:00,  8.46s/it]

2025/07/23 16:10:35 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/23 16:10:35 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2025/07/23 16:10:35 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0]
2025/07/23 16:10:35 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 30.0
2025/07/23 16:10:35 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/23 16:10:35 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 4 / 20 =====

🏃 View run eval_full_2 at: http://localhost:5000/#/experiments/1/runs/1583038d98e14f96bb0c924d3cfebbaa
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 1.00 / 10 (10.0%): 100%|██████████| 10/10 [01:16<00:00,  7.60s/it]

2025/07/23 16:11:51 INFO dspy.evaluate.evaluate: Average Metric: 1 / 10 (10.0%)
2025/07/23 16:11:51 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 10.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 0'].
2025/07/23 16:11:51 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0]
2025/07/23 16:11:51 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 30.0
2025/07/23 16:11:51 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/23 16:11:51 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 5 / 20 =====

🏃 View run eval_full_3 at: http://localhost:5000/#/experiments/1/runs/8c22a8738ff74242a8a9394ff0be9edc
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 1.00 / 10 (10.0%): 100%|██████████| 10/10 [01:11<00:00,  7.17s/it]

2025/07/23 16:13:03 INFO dspy.evaluate.evaluate: Average Metric: 1 / 10 (10.0%)
2025/07/23 16:13:03 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 10.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/23 16:13:03 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0]
2025/07/23 16:13:03 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 30.0
2025/07/23 16:13:03 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/23 16:13:03 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 6 / 20 =====

🏃 View run eval_full_4 at: http://localhost:5000/#/experiments/1/runs/5a35c5b819aa48d09085c727ac51fece
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [01:13<00:00,  7.34s/it]

2025/07/23 16:14:17 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/23 16:14:17 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2025/07/23 16:14:17 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0, 30.0]
2025/07/23 16:14:17 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 30.0
2025/07/23 16:14:17 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/23 16:14:17 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 7 / 20 =====

🏃 View run eval_full_5 at: http://localhost:5000/#/experiments/1/runs/3e32d1c87a4345bfae71450fd699a52d
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 0.00 / 10 (0.0%): 100%|██████████| 10/10 [01:25<00:00,  8.60s/it]

2025/07/23 16:15:43 INFO dspy.evaluate.evaluate: Average Metric: 0 / 10 (0.0%)
2025/07/23 16:15:43 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 0'].
2025/07/23 16:15:43 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0, 30.0, 0.0]
2025/07/23 16:15:43 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 30.0
2025/07/23 16:15:43 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/23 16:15:43 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 8 / 20 =====

🏃 View run eval_full_6 at: http://localhost:5000/#/experiments/1/runs/35802f7628894826a7487b9b54748e3e
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [01:11<00:00,  7.19s/it]

2025/07/23 16:16:55 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)
2025/07/23 16:16:55 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/07/23 16:16:55 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0, 30.0, 0.0, 20.0]
2025/07/23 16:16:55 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 30.0
2025/07/23 16:16:55 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/23 16:16:55 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 9 / 20 =====

🏃 View run eval_full_7 at: http://localhost:5000/#/experiments/1/runs/cfb32624cd534bae924a97bb510f5d42
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [01:37<00:00,  9.71s/it]

2025/07/23 16:18:33 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)
2025/07/23 16:18:33 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 0'].
2025/07/23 16:18:33 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0, 30.0, 0.0, 20.0, 20.0]
2025/07/23 16:18:33 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 30.0
2025/07/23 16:18:33 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/23 16:18:33 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 10 / 20 =====

🏃 View run eval_full_8 at: http://localhost:5000/#/experiments/1/runs/265965b555654623a37234f02762107b
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [01:09<00:00,  6.94s/it]

2025/07/23 16:19:42 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/23 16:19:42 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far! Score: 40.0
2025/07/23 16:19:42 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/23 16:19:42 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0, 30.0, 0.0, 20.0, 20.0, 40.0]
2025/07/23 16:19:42 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/23 16:19:42 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 16:19:42 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 11 / 20 =====

🏃 View run eval_full_9 at: http://localhost:5000/#/experiments/1/runs/116fff5f2b5d4eda98c8290d2ddb212d
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [01:30<00:00,  9.07s/it]

2025/07/23 16:21:13 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/23 16:21:13 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 4', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 3'].
2025/07/23 16:21:13 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0, 30.0, 0.0, 20.0, 20.0, 40.0, 30.0]
2025/07/23 16:21:13 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/23 16:21:13 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 16:21:13 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 12 / 20 =====

🏃 View run eval_full_10 at: http://localhost:5000/#/experiments/1/runs/dd61ce7181b74a93bd37c210aec4cb89
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 5.00 / 10 (50.0%): 100%|██████████| 10/10 [01:05<00:00,  6.56s/it]

2025/07/23 16:22:19 INFO dspy.evaluate.evaluate: Average Metric: 5 / 10 (50.0%)
2025/07/23 16:22:19 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far! Score: 50.0
2025/07/23 16:22:19 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 50.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 4'].
2025/07/23 16:22:19 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0, 30.0, 0.0, 20.0, 20.0, 40.0, 30.0, 50.0]
2025/07/23 16:22:19 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/23 16:22:19 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 16:22:19 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 13 / 20 =====

🏃 View run eval_full_11 at: http://localhost:5000/#/experiments/1/runs/434433610eed4ccbbf139c53317c0c18
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 5.00 / 10 (50.0%): 100%|██████████| 10/10 [01:00<00:00,  6.05s/it]

2025/07/23 16:23:20 INFO dspy.evaluate.evaluate: Average Metric: 5 / 10 (50.0%)
2025/07/23 16:23:20 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 50.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/23 16:23:20 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0, 30.0, 0.0, 20.0, 20.0, 40.0, 30.0, 50.0, 50.0]
2025/07/23 16:23:20 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/23 16:23:20 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 16:23:20 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 14 / 20 =====

🏃 View run eval_full_12 at: http://localhost:5000/#/experiments/1/runs/16399878df044d7ca5e9b896f1866eea
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [01:28<00:00,  8.84s/it]

2025/07/23 16:24:48 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)
2025/07/23 16:24:48 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 4'].
2025/07/23 16:24:48 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0, 30.0, 0.0, 20.0, 20.0, 40.0, 30.0, 50.0, 50.0, 20.0]
2025/07/23 16:24:48 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/23 16:24:48 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 16:24:48 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 15 / 20 =====

🏃 View run eval_full_13 at: http://localhost:5000/#/experiments/1/runs/89464f1cfa3847ecb0b3be21337aaac2
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [01:28<00:00,  8.82s/it]

2025/07/23 16:26:17 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/23 16:26:17 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 4'].
2025/07/23 16:26:17 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0, 30.0, 0.0, 20.0, 20.0, 40.0, 30.0, 50.0, 50.0, 20.0, 30.0]
2025/07/23 16:26:17 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/23 16:26:17 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 16:26:17 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 16 / 20 =====

🏃 View run eval_full_14 at: http://localhost:5000/#/experiments/1/runs/e17aaa00a39e44a989915ab3e7fe5da6
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [01:09<00:00,  6.95s/it]

2025/07/23 16:27:26 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)
2025/07/23 16:27:27 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 3', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 5'].
2025/07/23 16:27:27 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0, 30.0, 0.0, 20.0, 20.0, 40.0, 30.0, 50.0, 50.0, 20.0, 30.0, 20.0]
2025/07/23 16:27:27 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/23 16:27:27 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 16:27:27 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 17 / 20 =====

🏃 View run eval_full_15 at: http://localhost:5000/#/experiments/1/runs/e1dd83bfb416407f9151c69949dc134e
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [02:17<00:00, 13.79s/it]

2025/07/23 16:29:45 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/23 16:29:45 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 1', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 5'].
2025/07/23 16:29:45 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0, 30.0, 0.0, 20.0, 20.0, 40.0, 30.0, 50.0, 50.0, 20.0, 30.0, 20.0, 30.0]
2025/07/23 16:29:45 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/23 16:29:45 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 16:29:45 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 18 / 20 =====

🏃 View run eval_full_16 at: http://localhost:5000/#/experiments/1/runs/bb0d6a325c9b49a195cb9d777a318ec5
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [03:40<00:00, 22.06s/it]

2025/07/23 16:33:25 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/23 16:33:25 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 4'].
2025/07/23 16:33:25 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0, 30.0, 0.0, 20.0, 20.0, 40.0, 30.0, 50.0, 50.0, 20.0, 30.0, 20.0, 30.0, 30.0]
2025/07/23 16:33:25 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/23 16:33:25 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 16:33:25 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 19 / 20 =====

🏃 View run eval_full_17 at: http://localhost:5000/#/experiments/1/runs/c49217e193b940ce80d8eccc7b011a8c
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [03:07<00:00, 18.79s/it]

2025/07/23 16:36:34 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/23 16:36:34 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/07/23 16:36:34 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0, 30.0, 0.0, 20.0, 20.0, 40.0, 30.0, 50.0, 50.0, 20.0, 30.0, 20.0, 30.0, 30.0, 30.0]
2025/07/23 16:36:34 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/23 16:36:34 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 16:36:34 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 20 / 20 =====

🏃 View run eval_full_18 at: http://localhost:5000/#/experiments/1/runs/ae61119201934585a7c647127620b486
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 1.00 / 10 (10.0%): 100%|██████████| 10/10 [02:57<00:00, 17.74s/it]

2025/07/23 16:39:31 INFO dspy.evaluate.evaluate: Average Metric: 1 / 10 (10.0%)
2025/07/23 16:39:31 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 10.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 3', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 4'].
2025/07/23 16:39:31 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0, 30.0, 0.0, 20.0, 20.0, 40.0, 30.0, 50.0, 50.0, 20.0, 30.0, 20.0, 30.0, 30.0, 30.0, 10.0]
2025/07/23 16:39:31 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/23 16:39:31 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 16:39:31 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 21 / 20 =====

🏃 View run eval_full_19 at: http://localhost:5000/#/experiments/1/runs/b626991cb82948a2bdf4acd7ca0e864f
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [03:04<00:00, 18.44s/it]

2025/07/23 16:42:36 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)
2025/07/23 16:42:36 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 1'].
2025/07/23 16:42:36 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 30.0, 30.0, 10.0, 10.0, 30.0, 0.0, 20.0, 20.0, 40.0, 30.0, 50.0, 50.0, 20.0, 30.0, 20.0, 30.0, 30.0, 30.0, 10.0, 20.0]
2025/07/23 16:42:36 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/23 16:42:36 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 16:42:36 INFO dspy.teleprompt.mipro_optimizer_v2: Returning best identified program with score 50.0!

🏃 View run eval_full_20 at: http://localhost:5000/#/experiments/1/runs/c1d723d8415443959b8ff2569bdb403b
🧪 View experiment at: http://localhost:5000/#/experiments/1

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

🏃 View run powerful-dog-97 at: http://localhost:5000/#/experiments/1/runs/fe92b8138624478298b3dbcbd1d61b79
🧪 View experiment at: http://localhost:5000/#/experiments/1

[Trace(trace_id=89d2b7580cf74260b71f2323008293d4), Trace(trace_id=de767efbe6cd4de0bf8d26c323bc428b), Trace(trace_id=39cde7d56ed4475cb557f41377500844), Trace(trace_id=9269a59b693a4898a020929142c28c07), Trace(trace_id=5235f728675d4f8fa4f6b9553ea16997), Trace(trace_id=e1206c2c921c4f688729b451f7db60df), Trace(trace_id=fe74adcb40ab45039a87dd57f3e022d6), Trace(trace_id=b47aa060526247539b45255ff32f372b), Trace(trace_id=3422484e415f4783beb1e80ffe7f7c53), Trace(trace_id=090125432316499992a97cceabd6e2a2)]

2025/07/23 16:46:49 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.

In [18]:
evaluator = Evaluate(
    metric=dspy.evaluate.answer_exact_match,
    devset=valset,
    display_table=True,
    display_progress=True,
    num_threads=8,
)

In [21]:
original_score = evaluator(react)
original_score

  0%|          | 0/100 [03:22<?, ?it/s]         | 8/100 [00:57<05:01,  3.27s/it]
Average Metric: 13.00 / 100 (13.0%): 100%|██████████| 100/100 [34:18<00:00, 20.59s/it]

2025/07/23 18:24:32 INFO dspy.evaluate.evaluate: Average Metric: 13 / 100 (13.0%)

,question,example_answer,trajectory,reasoning,pred_answer,answer_exact_match
0,"What movie did ""the king of cool"" play in with Bud Ekins as his st...","""The Great Escape""","{'thought_0': 'I need to search Wikipedia for the movie ""The King ...","The information from the observations confirms that ""The King of C...","The movie was ""The Great Escape.""",
1,whos family had their own reality tv show. Robert Kardashian or Ma...,their family reality television series,"{'thought_0': ""I need to confirm which of the two individuals' fam...",The information confirms that Robert Kardashian's family has their...,Robert Kardashian's family had their own reality TV show.,
2,Which star in Shadows in Paradise is a Russian ballerina?,Sofya Skya,{'thought_0': 'I need to search for information about the star in ...,The search results indicate that Sofya Skya is a Russian ballerina...,"Sofya Skya is the Russian ballerina star in ""Shadows in Paradise.""",
3,What was the meaning of the name of the man who appointed Amashsai?,comforter,"{'thought_0': 'The name ""Amashsai"" might refer to a historical fig...","The name ""Amashsai"" is associated with a biblical figure, Amashsai...","Amashsai was appointed by Nehemiah, a biblical figure who assigned...",
4,"In addition to the Austrian passport, what is needed to gain acces...",national identity card,{'thought_0': 'I need to determine what additional documents are r...,The Austrian passport allows visa-free access to 173 countries and...,No additional documents are needed beyond the Austrian passport fo...,
...,...,...,...,...,...,...
95,"What date did the American actress and singer-songwriter, known fo...","April 19, 1994",{'thought_0': 'I need to find the release date of the first album ...,The search results indicate conflicting information about the firs...,The American actress and singer-songwriter Joanna Lumley released ...,
96,What animated creatures were the title characters of the film whic...,seals,"{'thought_0': ""I need to determine which of Shakespeare's early pl...","The search results indicate that ""Shakespeare: The Animated Tales""...",There is no film based on a Shakespearean play from early in his c...,
97,The 1925 Saint Mary's Gaels football team represented what private...,Saint Mary's College of California,"{'thought_0': ""I need to determine which private, coeducational co...",The information from the observations confirms that the 1925 Saint...,"Saint Mary's College of California in Moraga, California.",
98,Were Dorothy Arzner and Richard Wallace both French film directors?,no,{'thought_0': 'I need to verify the nationalities of Dorothy Arzne...,The reasoning is based on verifying the nationalities of Dorothy A...,"No, Dorothy Arzner was American, and Richard Wallace was not Frenc...",
99,Which artist started recording/performing earlier David Donato or ...,Moya Brennan,{'thought_0': 'I need to verify the debut years of David Donato an...,Both David Donato and Moya Brennan began their careers in 1970. Mo...,"Both artists started recording/performing in the same year, 1970. ...",

🏃 View run eval at: http://localhost:5000/#/experiments/1/runs/bd43f60cf99c4012b9d780f9204be10d
🧪 View experiment at: http://localhost:5000/#/experiments/1

13.0

[Trace(trace_id=471f08a902244058b60780e86e7536be), Trace(trace_id=81a98f47e0654c5fafc1504178e2e90e), Trace(trace_id=3a1063fa75f94f489158c745351e6504), Trace(trace_id=3b3681f1974c4797862846986e3efdf6), Trace(trace_id=2c215893afa24e78ad202d6f7b6423ed), Trace(trace_id=305c4694b33f43c783b374ee81731f69), Trace(trace_id=471afbd5bb464585a9b2c25be6db1bb7), Trace(trace_id=7eed1891a0744ffda85b442be20c7f65), Trace(trace_id=dcea82abf82d4fbb9e037d85a023e61b), Trace(trace_id=e37fc55b9f5942b88e80502cbd2bbcb1)]

In [22]:
optimized_score = evaluator(optimized_react)
optimized_score

Average Metric: 36.00 / 100 (36.0%): 100%|██████████| 100/100 [15:36<00:00,  9.37s/it]

2025/07/23 18:45:45 INFO dspy.evaluate.evaluate: Average Metric: 36 / 100 (36.0%)

,question,example_answer,trajectory,reasoning,pred_answer,answer_exact_match
0,"What movie did ""the king of cool"" play in with Bud Ekins as his st...","""The Great Escape""","{'thought_0': 'I need to find out which movie ""The King of Cool"" s...",The information from the observations indicates that Bud Ekins was...,The Great Escape,✔️ [True]
1,whos family had their own reality tv show. Robert Kardashian or Ma...,their family reality television series,"{'thought_0': ""I need to confirm which of Robert Kardashian or Man...",The information from the observations confirms that Robert Kardash...,Robert Kardashian's family,
2,Which star in Shadows in Paradise is a Russian ballerina?,Sofya Skya,{'thought_0': 'I need to search for information about the star in ...,"The search results for ""Shadows in Paradise"" cast members do not i...","There is no Russian ballerina in the cast of ""Shadows in Paradise.""",
3,What was the meaning of the name of the man who appointed Amashsai?,comforter,{'thought_0': 'I need to determine who the man who appointed Amash...,"The name Nehemiah means ""Yahweh comforts"" or ""Comforter,"" as deriv...","Nehemiah means ""Yahweh comforts"" or ""Comforter.""",
4,"In addition to the Austrian passport, what is needed to gain acces...",national identity card,{'thought_0': 'I need to determine what additional documents are r...,The information from the observations indicates that Austrian citi...,No additional documents are needed beyond the Austrian passport.,
...,...,...,...,...,...,...
95,"What date did the American actress and singer-songwriter, known fo...","April 19, 1994","{'thought_0': ""I need to search Wikipedia to find the release date...",The information from the observations confirms that Barbara Eden's...,1984,
96,What animated creatures were the title characters of the film whic...,seals,{'thought_0': 'I need to confirm which animated creature is from t...,"The search results indicate that ""The Journey to Melonia"" is the f...",The animated creature's name is not explicitly mentioned in the pr...,
97,The 1925 Saint Mary's Gaels football team represented what private...,Saint Mary's College of California,"{'thought_0': ""I need to search Wikipedia for information about th...",The information from the observations confirms that the 1925 Saint...,Saint Mary's College of California,✔️ [True]
98,Were Dorothy Arzner and Richard Wallace both French film directors?,no,{'thought_0': 'I need to verify the nationalities of Dorothy Arzne...,The information from the observations indicates that Dorothy Arzne...,no,✔️ [True]
99,Which artist started recording/performing earlier David Donato or ...,Moya Brennan,{'thought_0': 'I need to research the debut dates of David Donato ...,The information indicates that Moya Brennan began performing profe...,Moya Brennan,✔️ [True]

🏃 View run eval at: http://localhost:5000/#/experiments/1/runs/589f0ddc2af243d1967d6b8e4e3900dd
🧪 View experiment at: http://localhost:5000/#/experiments/1

36.0

[Trace(trace_id=f5919f1ee87d418b85edc86b1e56c29f), Trace(trace_id=1c1d939229be4f44b2665a058d797e4e), Trace(trace_id=67da43d94e39482581e6c58309ea9684), Trace(trace_id=f655c1ecb6fd4ee89b9df80291ac0d6c), Trace(trace_id=89517f1d322740f48e153d4cbb0467ce), Trace(trace_id=710114264901422090a5c59928ccf239), Trace(trace_id=0175a364bb2549be91f298002d140cb1), Trace(trace_id=a06d341624294684a0d0ef43b3ee87bd), Trace(trace_id=a3e8b4667fbe44f380c2124680629777), Trace(trace_id=facf78dd0a2741e7952a6f33ee6eaf05)]

### qwen3:4b

In [33]:
lm = LM(
    "ollama_chat/qwen3:4b",
    api_base="http://localhost:11434",
    api_key="",
    max_tokens=40960,
    temperature=0.0,
    cache=False,
)
dspy.configure(lm=lm)

In [34]:
react = ReAct("question -> answer", tools=[search_wikipedia])

In [35]:
tp = MIPROv2(
    metric=dspy.evaluate.answer_exact_match,
    auto="light",
    num_threads=8,
)

In [36]:
optimized_react = tp.compile(
    react,
    trainset=trainset[:10],
    valset=valset[:10],
    requires_permission_to_run=False,
)

2025/07/23 19:40:04 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '8ce79430ad024094b1e8dc1a7e5b7b37', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current dspy workflow
2025/07/23 19:40:04 INFO dspy.teleprompt.mipro_optimizer_v2:
RUNNING WITH THE FOLLOWING LIGHT AUTO RUN SETTINGS:
num_trials: 20
minibatch: False
num_fewshot_candidates: 6
num_instruct_candidates: 3
valset size: 10

2025/07/23 19:40:04 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 1: BOOTSTRAP FEWSHOT EXAMPLES <==
2025/07/23 19:40:04 INFO dspy.teleprompt.mipro_optimizer_v2: These will be used as few-shot example candidates for our program and for creating instructions.

2025/07/23 19:40:04 INFO dspy.teleprompt.mipro_optimizer_v2: Bootstrapping N=6 sets of demonstrations...

Bootstrapping set 1/6
Bootstrapping set 2/6
Bootstrapping set 3/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

100%|██████████| 10/10 [13:51<00:00, 83.15s/it]

Bootstrapped 2 full traces after 9 examples for up to 1 rounds, amounting to 10 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 4/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

 80%|████████  | 8/10 [13:07<03:16, 98.46s/it]

Bootstrapped 2 full traces after 8 examples for up to 1 rounds, amounting to 8 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 5/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

 10%|█         | 1/10 [00:19<02:56, 19.60s/it]

Bootstrapped 1 full traces after 1 examples for up to 1 rounds, amounting to 1 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 6/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

100%|██████████| 10/10 [33:37<00:00, 201.79s/it]

Bootstrapped 2 full traces after 9 examples for up to 1 rounds, amounting to 10 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

2025/07/23 20:41:05 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 2: PROPOSE INSTRUCTION CANDIDATES <==
2025/07/23 20:41:05 INFO dspy.teleprompt.mipro_optimizer_v2: We will use the few-shot examples from the previous step, a generated dataset summary, a summary of the program code, and a randomly selected prompting tip to propose instructions.
2025/07/23 20:41:16 INFO dspy.teleprompt.mipro_optimizer_v2:
Proposing N=3 instructions...

2025/07/23 20:44:24 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 0:

2025/07/23 20:44:24 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the fields `question`, produce the fields `answer`.

You are an Agent. In each episode, you will be given the fields `question` as input. And you can see your past trajectory so far.
Your goal is to use one or more of the supplied tools to collect any necessary information for producing `answer`.

To do this, you will interleave next_thought, next_tool_name, and next_tool_args in each turn, and also when finishing the task.
After each tool call, you receive a resulting observation, which gets appended to your trajectory.

When writing next_thought, you may reason about the current situation and plan for future steps.
When selecting the next_tool_name and its next_tool_args, the tool must be one of:

(1) search_wikipedia. It takes arguments {'query': {'type': 'string'}}.
(2) finish, whose description is <desc>Marks the task as complete. That is, signals that all information for producing the outputs, i.e. `answer`, are now available to be extracted.</desc>. It takes arguments {}.
When providing `next_tool_args`, the value inside the field must be in JSON format

2025/07/23 20:44:24 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Given the fields `question`, produce the fields `answer`.

You are an Agent. In each episode, you will be given the fields `question` as input. And you can see your past trajectory so far.
Your goal is to use one or more of the supplied tools to collect any necessary information for producing `answer`.

To do this, you will interleave `next_thought`, `next_tool_name`, and `next_tool_args` in each turn, and also when finishing the task.
After each tool call, you receive a resulting observation, which gets appended to your trajectory.

When writing `next_thought`, you may reason about the current situation and plan for future steps.
When selecting `next_tool_name` and its `next_tool_args`, the tool must be one of:
(1) `search_wikipedia`. It takes arguments `{"query": "string"}`.
(2) `finish`, whose description is `<desc>Marks the task as complete. That is, signals that all information for producing the outputs, i.e. `answer`, are now available to be extracted.</desc>`. It takes arguments `{}`.
When providing `next_tool_args`, the value inside the field must be in JSON format.

2025/07/23 20:44:24 INFO dspy.teleprompt.mipro_optimizer_v2: 2: I need to determine the production studio of "Never a Dull Moment" to confirm if it is also produced by Walt Disney Productions. I will search Wikipedia for "Never a Dull Moment" to verify.
Next Tool Name: search_wikipedia
Next Tool Args: {"query": "Never a Dull Moment"}

2025/07/23 20:44:24 INFO dspy.teleprompt.mipro_optimizer_v2:

2025/07/23 20:44:24 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 1:

2025/07/23 20:44:24 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the fields `question`, produce the fields `answer`.

2025/07/23 20:44:24 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Given a question asking for the production studio of two films, search Wikipedia for each film title to identify the studio mentioned. Extract the studio name from each result and confirm that both films are associated with the same studio. Provide the name of the studio as the answer.

2025/07/23 20:44:24 INFO dspy.teleprompt.mipro_optimizer_v2: 2: Given the question and the context provided (search results from Wikipedia), identify the production studio of the two films mentioned in the question. The answer should be the studio explicitly stated in the context for both films.

2025/07/23 20:44:24 INFO dspy.teleprompt.mipro_optimizer_v2:

2025/07/23 20:44:24 INFO dspy.teleprompt.mipro_optimizer_v2: ==> STEP 3: FINDING OPTIMAL PROMPT PARAMETERS <==
2025/07/23 20:44:24 INFO dspy.teleprompt.mipro_optimizer_v2: We will evaluate the program over a series of trials with different combinations of instructions and few-shot examples to find the optimal combination using Bayesian Optimization.

2025/07/23 20:44:24 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 1 / 20 - Full Evaluation of Default Program ==

Average Metric: 0.00 / 10 (0.0%): 100%|██████████| 10/10 [02:50<00:00, 17.05s/it]

2025/07/23 20:47:14 INFO dspy.evaluate.evaluate: Average Metric: 0 / 10 (0.0%)

🏃 View run eval_full_0 at: http://localhost:5000/#/experiments/1/runs/a3d1cb9dec874ebb9643a8eaed77d28a
🧪 View experiment at: http://localhost:5000/#/experiments/1

2025/07/23 20:47:14 INFO dspy.teleprompt.mipro_optimizer_v2: Default program score: 0.0

/home/eugene/projects/deeplearning.ai/.venv/lib/python3.13/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
2025/07/23 20:47:14 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 2 / 20 =====

Average Metric: 3.00 / 10 (30.0%): : 12it [05:06, 25.57s/it]

2025/07/23 20:52:21 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)

🏃 View run eval_full_1 at: http://localhost:5000/#/experiments/1/runs/33093080b21d47679fceaaf92c453dde
🧪 View experiment at: http://localhost:5000/#/experiments/1

2025/07/23 20:52:22 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far! Score: 30.0
2025/07/23 20:52:22 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 3', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 0'].
2025/07/23 20:52:22 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0]
2025/07/23 20:52:22 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 30.0
2025/07/23 20:52:22 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/23 20:52:22 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 3 / 20 =====

  0%|          | 0/10 [00:00<?, ?it/s]

2025/07/23 20:53:26 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.

Average Metric: 5.00 / 10 (50.0%): 100%|██████████| 10/10 [04:02<00:00, 24.24s/it]

2025/07/23 20:56:24 INFO dspy.evaluate.evaluate: Average Metric: 5 / 10 (50.0%)
2025/07/23 20:56:24 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far! Score: 50.0
2025/07/23 20:56:24 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 50.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2025/07/23 20:56:24 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0]
2025/07/23 20:56:24 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/23 20:56:24 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/23 20:56:24 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 4 / 20 =====

🏃 View run eval_full_2 at: http://localhost:5000/#/experiments/1/runs/480d8a9d18e24ec592e132a1b671445d
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [03:12<00:00, 19.28s/it]

2025/07/23 20:59:37 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/23 20:59:37 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 0'].
2025/07/23 20:59:37 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0]
2025/07/23 20:59:37 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/23 20:59:37 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/23 20:59:37 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 5 / 20 =====

🏃 View run eval_full_3 at: http://localhost:5000/#/experiments/1/runs/3e292e9a3466480e956b553ffa6d9753
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 5.00 / 10 (50.0%): 100%|██████████| 10/10 [03:19<00:00, 19.96s/it]

2025/07/23 21:02:57 INFO dspy.evaluate.evaluate: Average Metric: 5 / 10 (50.0%)
2025/07/23 21:02:57 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 50.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/23 21:02:57 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0]
2025/07/23 21:02:57 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/23 21:02:57 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/23 21:02:57 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 6 / 20 =====

🏃 View run eval_full_4 at: http://localhost:5000/#/experiments/1/runs/c8c1426d610f488b9f3c20b7c7f1fa0e
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 5.00 / 10 (50.0%): 100%|██████████| 10/10 [03:45<00:00, 22.52s/it]

2025/07/23 21:06:42 INFO dspy.evaluate.evaluate: Average Metric: 5 / 10 (50.0%)
2025/07/23 21:06:43 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 50.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2025/07/23 21:06:43 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0, 50.0]
2025/07/23 21:06:43 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/23 21:06:43 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/23 21:06:43 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 7 / 20 =====

🏃 View run eval_full_5 at: http://localhost:5000/#/experiments/1/runs/f1d3b836f2bf444ca6958c87ac97f36b
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [05:38<00:00, 33.83s/it]

2025/07/23 21:12:21 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)
2025/07/23 21:12:21 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 0'].
2025/07/23 21:12:21 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0, 50.0, 20.0]
2025/07/23 21:12:21 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/23 21:12:21 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/23 21:12:21 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 8 / 20 =====

🏃 View run eval_full_6 at: http://localhost:5000/#/experiments/1/runs/236387b60f394653a5570412f4140094
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 6.00 / 10 (60.0%): 100%|██████████| 10/10 [07:47<00:00, 46.75s/it]

2025/07/23 21:20:09 INFO dspy.evaluate.evaluate: Average Metric: 6 / 10 (60.0%)
2025/07/23 21:20:09 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far! Score: 60.0
2025/07/23 21:20:09 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 60.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/07/23 21:20:09 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0, 50.0, 20.0, 60.0]
2025/07/23 21:20:09 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/23 21:20:09 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/23 21:20:09 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 9 / 20 =====

🏃 View run eval_full_7 at: http://localhost:5000/#/experiments/1/runs/2518c47028054fa998b13d31153935f2
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [03:26<00:00, 20.62s/it]

2025/07/23 21:23:35 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/23 21:23:35 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 0'].
2025/07/23 21:23:35 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0, 50.0, 20.0, 60.0, 30.0]
2025/07/23 21:23:35 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/23 21:23:35 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/23 21:23:35 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 10 / 20 =====

🏃 View run eval_full_8 at: http://localhost:5000/#/experiments/1/runs/2aa86bf7a6694d19b2d2d83c25c1038b
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 6.00 / 10 (60.0%): 100%|██████████| 10/10 [02:51<00:00, 17.18s/it]

2025/07/23 21:26:27 INFO dspy.evaluate.evaluate: Average Metric: 6 / 10 (60.0%)
2025/07/23 21:26:27 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 60.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/23 21:26:27 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0, 50.0, 20.0, 60.0, 30.0, 60.0]
2025/07/23 21:26:27 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/23 21:26:27 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 21:26:27 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 11 / 20 =====

🏃 View run eval_full_9 at: http://localhost:5000/#/experiments/1/runs/46adcb05cce64955bc045f086f5694ac
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [03:21<00:00, 20.10s/it]

2025/07/23 21:29:48 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/23 21:29:48 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 1'].
2025/07/23 21:29:48 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0, 50.0, 20.0, 60.0, 30.0, 60.0, 40.0]
2025/07/23 21:29:48 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/23 21:29:48 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 21:29:48 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 12 / 20 =====

🏃 View run eval_full_10 at: http://localhost:5000/#/experiments/1/runs/f9223869cd9a4c59bfa19c2bddf11049
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 5.00 / 10 (50.0%): 100%|██████████| 10/10 [05:33<00:00, 33.32s/it]

2025/07/23 21:35:22 INFO dspy.evaluate.evaluate: Average Metric: 5 / 10 (50.0%)
2025/07/23 21:35:22 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 50.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/23 21:35:22 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0, 50.0, 20.0, 60.0, 30.0, 60.0, 40.0, 50.0]
2025/07/23 21:35:22 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/23 21:35:22 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 21:35:22 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 13 / 20 =====

🏃 View run eval_full_11 at: http://localhost:5000/#/experiments/1/runs/d112e3eb454745ed9232a5a187862801
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [10:12<00:00, 61.20s/it]

2025/07/23 21:45:34 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/23 21:45:34 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/07/23 21:45:34 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0, 50.0, 20.0, 60.0, 30.0, 60.0, 40.0, 50.0, 40.0]
2025/07/23 21:45:34 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/23 21:45:34 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 21:45:34 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 14 / 20 =====

🏃 View run eval_full_12 at: http://localhost:5000/#/experiments/1/runs/bcc6121f9a7d4f408988f7205a254944
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [03:50<00:00, 23.08s/it]

2025/07/23 21:49:25 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/23 21:49:25 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 3'].
2025/07/23 21:49:25 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0, 50.0, 20.0, 60.0, 30.0, 60.0, 40.0, 50.0, 40.0, 30.0]
2025/07/23 21:49:25 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/23 21:49:25 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 21:49:25 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 15 / 20 =====

🏃 View run eval_full_13 at: http://localhost:5000/#/experiments/1/runs/8a792ef5d5a747c083bddf29203d9ce4
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 5.00 / 10 (50.0%): 100%|██████████| 10/10 [03:32<00:00, 21.25s/it]

2025/07/23 21:52:58 INFO dspy.evaluate.evaluate: Average Metric: 5 / 10 (50.0%)
2025/07/23 21:52:58 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 50.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 4', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/07/23 21:52:58 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0, 50.0, 20.0, 60.0, 30.0, 60.0, 40.0, 50.0, 40.0, 30.0, 50.0]
2025/07/23 21:52:58 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/23 21:52:58 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 21:52:58 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 16 / 20 =====

🏃 View run eval_full_14 at: http://localhost:5000/#/experiments/1/runs/d3b3cd4412524e89bf44ae3acb2a7a34
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 5.00 / 10 (50.0%): 100%|██████████| 10/10 [05:34<00:00, 33.46s/it]

2025/07/23 21:58:32 INFO dspy.evaluate.evaluate: Average Metric: 5 / 10 (50.0%)
2025/07/23 21:58:32 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 50.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 5'].
2025/07/23 21:58:32 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0, 50.0, 20.0, 60.0, 30.0, 60.0, 40.0, 50.0, 40.0, 30.0, 50.0, 50.0]
2025/07/23 21:58:32 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/23 21:58:32 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 21:58:32 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 17 / 20 =====

🏃 View run eval_full_15 at: http://localhost:5000/#/experiments/1/runs/56c8165c5e8740c1be21a617880f8153
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [03:54<00:00, 23.47s/it]

2025/07/23 22:02:27 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/23 22:02:27 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/23 22:02:27 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0, 50.0, 20.0, 60.0, 30.0, 60.0, 40.0, 50.0, 40.0, 30.0, 50.0, 50.0, 40.0]
2025/07/23 22:02:27 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/23 22:02:27 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 22:02:27 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 18 / 20 =====

🏃 View run eval_full_16 at: http://localhost:5000/#/experiments/1/runs/9b680d656cf24926a76872ee0b074085
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 6.00 / 10 (60.0%): 100%|██████████| 10/10 [05:09<00:00, 30.99s/it]

2025/07/23 22:07:37 INFO dspy.evaluate.evaluate: Average Metric: 6 / 10 (60.0%)
2025/07/23 22:07:37 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 60.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 3'].
2025/07/23 22:07:37 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0, 50.0, 20.0, 60.0, 30.0, 60.0, 40.0, 50.0, 40.0, 30.0, 50.0, 50.0, 40.0, 60.0]
2025/07/23 22:07:37 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/23 22:07:37 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 22:07:37 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 19 / 20 =====

🏃 View run eval_full_17 at: http://localhost:5000/#/experiments/1/runs/fade58cc7479435ab5b71364b8a3cba9
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [06:46<00:00, 40.65s/it]

2025/07/23 22:14:24 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/23 22:14:24 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 1', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 5'].
2025/07/23 22:14:24 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0, 50.0, 20.0, 60.0, 30.0, 60.0, 40.0, 50.0, 40.0, 30.0, 50.0, 50.0, 40.0, 60.0, 40.0]
2025/07/23 22:14:24 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/23 22:14:24 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 22:14:24 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 20 / 20 =====

🏃 View run eval_full_18 at: http://localhost:5000/#/experiments/1/runs/b4ce59cf917447729a7cc6c55a80e661
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 6.00 / 10 (60.0%): 100%|██████████| 10/10 [05:57<00:00, 35.71s/it]

2025/07/23 22:20:21 INFO dspy.evaluate.evaluate: Average Metric: 6 / 10 (60.0%)
2025/07/23 22:20:21 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 60.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 3', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 4'].
2025/07/23 22:20:21 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0, 50.0, 20.0, 60.0, 30.0, 60.0, 40.0, 50.0, 40.0, 30.0, 50.0, 50.0, 40.0, 60.0, 40.0, 60.0]
2025/07/23 22:20:21 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/23 22:20:21 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 22:20:21 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 21 / 20 =====

🏃 View run eval_full_19 at: http://localhost:5000/#/experiments/1/runs/8f38c44dfa494f5cafa2b557de3f0458
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [02:52<00:00, 17.23s/it]

2025/07/23 22:23:14 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/23 22:23:14 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/07/23 22:23:14 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 30.0, 50.0, 30.0, 50.0, 50.0, 20.0, 60.0, 30.0, 60.0, 40.0, 50.0, 40.0, 30.0, 50.0, 50.0, 40.0, 60.0, 40.0, 60.0, 40.0]
2025/07/23 22:23:14 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/23 22:23:14 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/23 22:23:14 INFO dspy.teleprompt.mipro_optimizer_v2: Returning best identified program with score 60.0!

🏃 View run eval_full_20 at: http://localhost:5000/#/experiments/1/runs/419ffb6e53e1446b8e42d00afac603c8
🧪 View experiment at: http://localhost:5000/#/experiments/1

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

🏃 View run luminous-jay-870 at: http://localhost:5000/#/experiments/1/runs/8ce79430ad024094b1e8dc1a7e5b7b37
🧪 View experiment at: http://localhost:5000/#/experiments/1

[Trace(trace_id=a4458a0bbbf043e9b2592b9197a2d255), Trace(trace_id=3d72a4247e13414cb742245d79cd566e), Trace(trace_id=681b40298d954dc5b8a9f88df8bde431), Trace(trace_id=e5785b1ecfcd46ba8b19496265f0e445), Trace(trace_id=b8cd4172da694c8a85f27a271df47981), Trace(trace_id=ce16ed443f87423c90c5aa566a8b7083), Trace(trace_id=ae849dd9e5a44536b5db2811dab98465), Trace(trace_id=1130ed837ad24dddb020dc1f916030cf), Trace(trace_id=f300cb8f4cc74a9bb669a37cde4b73c1), Trace(trace_id=d44dcb9fbc7f4848821268e9d719e19d)]

In [37]:
evaluator = Evaluate(
    metric=dspy.evaluate.answer_exact_match,
    devset=valset,
    display_table=True,
    display_progress=True,
    num_threads=8,
)

In [38]:
original_score = evaluator(react)
original_score

Average Metric: 26.00 / 100 (26.0%): 100%|██████████| 100/100 [51:00<00:00, 30.61s/it]

2025/07/23 23:14:15 INFO dspy.evaluate.evaluate: Average Metric: 26 / 100 (26.0%)

,question,example_answer,trajectory,reasoning,pred_answer,answer_exact_match
0,"What movie did ""the king of cool"" play in with Bud Ekins as his st...","""The Great Escape""","{'thought_0': 'I need to determine which movie features ""the king ...",The search for Bud Ekins' stunt double movies identified films lik...,There is no movie mentioned in the provided information where Pete...,
1,whos family had their own reality tv show. Robert Kardashian or Ma...,their family reality television series,"{'thought_0': 'I need to determine which family, Robert Kardashian...",The search results confirm that Robert Kardashian's family is asso...,"Robert Kardashian's family had their own reality TV show, ""Keeping...",
2,Which star in Shadows in Paradise is a Russian ballerina?,Sofya Skya,"{'thought_0': 'The question asks about a specific character in ""Sh...","The question refers to ""Shadows in Paradise,"" which has two distin...","The provided information does not specify a Russian ballerina in ""...",
3,What was the meaning of the name of the man who appointed Amashsai?,comforter,{'thought_0': 'To determine the meaning of the name of the man who...,"The man who appointed Amashsai is Nehemiah, as established through...","The meaning of the name Nehemiah is ""Yahweh comforts"" or ""comforter.""",
4,"In addition to the Austrian passport, what is needed to gain acces...",national identity card,"{'thought_0': ""To determine what additional documents are required...",The observation from the Wikipedia search confirms that Austrian c...,No additional documents are required beyond the Austrian passport ...,
...,...,...,...,...,...,...
95,"What date did the American actress and singer-songwriter, known fo...","April 19, 1994",{'thought_0': 'To determine the release date of the first album by...,The actress associated with the role of Peggy Bundy is Katey Sagal...,The American actress and singer-songwriter known for her role as P...,
96,What animated creatures were the title characters of the film whic...,seals,"{'thought_0': ""The question asks for animated creatures that were ...","The film ""Gnomeo & Juliet"" (2011) is based on Shakespeare's ""Romeo...",Romeo and Juliet,
97,The 1925 Saint Mary's Gaels football team represented what private...,Saint Mary's College of California,"{'thought_0': 'The question asks for the private, coeducational co...",The search results confirm that the 1925 Saint Mary's Gaels footba...,Saint Mary's College of California,✔️ [True]
98,Were Dorothy Arzner and Richard Wallace both French film directors?,no,"{'thought_0': ""I need to verify the nationalities of Dorothy Arzne...","Dorothy Arzner was confirmed to be an American film director, not ...","No, Dorothy Arzner was an American film director, and Richard Wall...",
99,Which artist started recording/performing earlier David Donato or ...,Moya Brennan,"{'thought_0': ""I need to determine the recording/performing start ...","Moya Brennan began performing professionally in 1970, as stated in...",Moya Brennan started recording/performing earlier than David Donato.,

🏃 View run eval at: http://localhost:5000/#/experiments/1/runs/d0d073789fe045d28abc4a2303bb528f
🧪 View experiment at: http://localhost:5000/#/experiments/1

26.0

[Trace(trace_id=14e2c163770d4ce08dee1d56e3be8d26), Trace(trace_id=38f73f4681844e76a12322343ef0bd42), Trace(trace_id=b60b8bef35eb41289e5e9a041604470b), Trace(trace_id=af0632839d7a4cb1a378f7d72dd20a23), Trace(trace_id=691eb5d98b1e4f5dafdbb79644191f49), Trace(trace_id=ff767eaa0da349688e79b9b835172ab4), Trace(trace_id=d8757c7ea51146c98eb799ca2b434f5f), Trace(trace_id=5d1d49bbdf7b4e649f55922e257e8c56), Trace(trace_id=6fe5627b764a4be2a716137511d177fd), Trace(trace_id=53741e2e62794a01ab04bbdfdd393f7f)]

In [39]:
optimized_score = evaluator(optimized_react)
optimized_score

Average Metric: 52.00 / 100 (52.0%): : 101it [1:08:54, 40.94s/it]

2025/07/24 00:23:10 INFO dspy.evaluate.evaluate: Average Metric: 52 / 100 (52.0%)

,question,example_answer,trajectory,reasoning,pred_answer,answer_exact_match
0,"What movie did ""the king of cool"" play in with Bud Ekins as his st...","""The Great Escape""","{'thought_0': 'I need to determine which movie features ""the king ...","The term ""the king of cool"" refers to Steve McQueen, a renowned ac...",The Great Escape,✔️ [True]
1,whos family had their own reality tv show. Robert Kardashian or Ma...,their family reality television series,"{'thought_0': ""I need to determine which family, Robert Kardashian...",The search results indicate that Robert Kardashian's family is ass...,Robert Kardashian,
2,Which star in Shadows in Paradise is a Russian ballerina?,Sofya Skya,"{'thought_0': 'I need to identify the Russian ballerina in ""Shadow...","The 2010 American film ""Shadows in Paradise"" features Sofya Skya a...",Sofya Skya,✔️ [True]
3,What was the meaning of the name of the man who appointed Amashsai?,comforter,{'thought_0': 'I need to determine who appointed Amashsai and the ...,The search results indicate that Amashsai was appointed by Nehemia...,"The name Nehemiah means ""Yahweh comforts"" or ""comforter.""",
4,"In addition to the Austrian passport, what is needed to gain acces...",national identity card,{'thought_0': 'I need to determine the additional requirements for...,The Austrian passport itself grants visa-free or visa-on-arrival a...,No additional documents are required beyond the Austrian passport.,
...,...,...,...,...,...,...
95,"What date did the American actress and singer-songwriter, known fo...","April 19, 1994",{'thought_0': 'I need to identify the American actress and singer-...,The American actress known for playing Peggy Bundy is Katey Sagal....,"April 19, 1994",✔️ [True]
96,What animated creatures were the title characters of the film whic...,seals,"{'thought_0': ""I need to find out which animated creatures were th...",The question asks for animated creatures as title characters of a ...,Romeo and Juliet,
97,The 1925 Saint Mary's Gaels football team represented what private...,Saint Mary's College of California,{'thought_0': 'I need to confirm that the 1925 Saint Mary\'s Gaels...,The 1925 Saint Mary's Gaels football team represented Saint Mary's...,Saint Mary's College of California,✔️ [True]
98,Were Dorothy Arzner and Richard Wallace both French film directors?,no,{'thought_0': 'I need to verify the nationalities and backgrounds ...,"Dorothy Arzner was an American film director, not French. Richard ...",no,✔️ [True]
99,Which artist started recording/performing earlier David Donato or ...,Moya Brennan,"{'thought_0': ""I need to determine the early career dates of David...",David Donato began recording with Black Sabbath in 1984-1985. Moya...,Moya Brennan,✔️ [True]

🏃 View run eval at: http://localhost:5000/#/experiments/1/runs/d47ed21946fe4125b5ae53ff403786b7
🧪 View experiment at: http://localhost:5000/#/experiments/1

52.0

[Trace(trace_id=e9f8e745a8294c91b86bdc456a89b871), Trace(trace_id=3da6f947280e4dce9ffa0834b16274e5), Trace(trace_id=a7aee9199b6b496dabde3aaf10ae474c), Trace(trace_id=c5cb93089ca542118c549860f907e2c4), Trace(trace_id=c314912c1b214198a432fe05f74efdd0), Trace(trace_id=453ccf7aa7ab4e33b864ef65b24c4191), Trace(trace_id=099a37793ea94721be5afd8cb27034e5), Trace(trace_id=7653fff3dea7403eb4973a5d2ca19d78), Trace(trace_id=add010e42c3740c6a586b796d99cb28c), Trace(trace_id=bf58cfb963ad4fd1a9cf0414269de595)]

### gemma3:4b

In [40]:
lm = LM(
    "ollama_chat/gemma3:4b",
    api_base="http://localhost:11434",
    api_key="",
    max_tokens=40960,
    temperature=0.0,
    cache=False,
)
dspy.configure(lm=lm)

In [41]:
react = ReAct("question -> answer", tools=[search_wikipedia])

In [42]:
tp = MIPROv2(
    metric=dspy.evaluate.answer_exact_match,
    auto="light",
    num_threads=8,
)

In [43]:
optimized_react = tp.compile(
    react,
    trainset=trainset[:10],
    valset=valset[:10],
    requires_permission_to_run=False,
)

2025/07/24 00:23:11 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'f977d1c7c55943c7becbe6e5fa9013a9', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current dspy workflow
2025/07/24 00:23:11 INFO dspy.teleprompt.mipro_optimizer_v2:
RUNNING WITH THE FOLLOWING LIGHT AUTO RUN SETTINGS:
num_trials: 20
minibatch: False
num_fewshot_candidates: 6
num_instruct_candidates: 3
valset size: 10

2025/07/24 00:23:11 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 1: BOOTSTRAP FEWSHOT EXAMPLES <==
2025/07/24 00:23:11 INFO dspy.teleprompt.mipro_optimizer_v2: These will be used as few-shot example candidates for our program and for creating instructions.

2025/07/24 00:23:11 INFO dspy.teleprompt.mipro_optimizer_v2: Bootstrapping N=6 sets of demonstrations...

Bootstrapping set 1/6
Bootstrapping set 2/6
Bootstrapping set 3/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

100%|██████████| 10/10 [02:52<00:00, 17.23s/it]

Bootstrapped 4 full traces after 9 examples for up to 1 rounds, amounting to 10 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 4/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

 70%|███████   | 7/10 [02:06<00:54, 18.08s/it]

Bootstrapped 2 full traces after 7 examples for up to 1 rounds, amounting to 7 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 5/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

 10%|█         | 1/10 [00:12<01:53, 12.58s/it]

Bootstrapped 1 full traces after 1 examples for up to 1 rounds, amounting to 1 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 6/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

 50%|█████     | 5/10 [01:40<01:40, 20.09s/it]

Bootstrapped 3 full traces after 5 examples for up to 1 rounds, amounting to 5 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

2025/07/24 00:30:04 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 2: PROPOSE INSTRUCTION CANDIDATES <==
2025/07/24 00:30:04 INFO dspy.teleprompt.mipro_optimizer_v2: We will use the few-shot examples from the previous step, a generated dataset summary, a summary of the program code, and a randomly selected prompting tip to propose instructions.
2025/07/24 00:30:13 INFO dspy.teleprompt.mipro_optimizer_v2:
Proposing N=3 instructions...

2025/07/24 00:30:37 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.
2025/07/24 00:32:29 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 0:

2025/07/24 00:32:29 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the fields `question`, produce the fields `answer`.

You are an Agent. In each episode, you will be given the fields `question` as input. And you can see your past trajectory so far.
Your goal is to use one or more of the supplied tools to collect any necessary information for producing `answer`.

To do this, you will interleave next_thought, next_tool_name, and next_tool_args in each turn, and also when finishing the task.
After each tool call, you receive a resulting observation, which gets appended to your trajectory.

When writing next_thought, you may reason about the current situation and plan for future steps.
When selecting the next_tool_name and its next_tool_args, the tool must be one of:

(1) search_wikipedia. It takes arguments {'query': {'type': 'string'}}.
(2) finish, whose description is <desc>Marks the task as complete. That is, signals that all information for producing the outputs, i.e. `answer`, are now available to be extracted.</desc>. It takes arguments {}.
When providing `next_tool_args`, the value inside the field must be in JSON format

2025/07/24 00:32:29 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Given the fields `question`, produce the fields `answer`.

You are an Agent. In each episode, you will be given the fields `question` as input. And you can see your past trajectory so far.
Your goal is to use one or more of the supplied tools to collect any necessary information for producing `answer`.

To do this, you will interleave next_thought, next_tool_name, and next_tool_args in each turn, and also when finishing the task.
After each tool call, you receive a resulting observation, which gets appended to your trajectory.

When writing next_thought, you may reason about the current situation and plan for future steps.
When selecting the next_tool_name and its next_tool_args, the tool must be one of:

(1) search_wikipedia. It takes arguments {'query': {'type': 'string'}}.
(2) finish, whose description is <desc>Marks the task as complete. That is, signals that all information for producing the outputs, i.e. `answer`, are now available to be extracted.</desc>. It takes arguments {}.
When providing `next_tool_args`, the value inside the field must be in JSON format

2025/07/24 00:32:29 INFO dspy.teleprompt.mipro_optimizer_v2: 2: Okay, let's investigate whether Truckin' Magazine and Girlfriends offer relationship advice. It seems like a strange combination, but I should check to see if either publication has a focus on relationships. I'll start by searching Wikipedia to see if there's any information about the content of each magazine.
Next Tool Name: search_wikipedia
Next Tool Args: {'query': 'Truckin’ Magazine content'}

2025/07/24 00:32:29 INFO dspy.teleprompt.mipro_optimizer_v2:

2025/07/24 00:32:29 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 1:

2025/07/24 00:32:29 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the fields `question`, produce the fields `answer`.

2025/07/24 00:32:29 INFO dspy.teleprompt.mipro_optimizer_v2: 1: You are a helpful assistant that can answer questions. You are given a question and you need to respond with the answer. You are given the fields `question` and `answer`. The `question` field contains the question to answer, and the `answer` field contains the answer. You need to respond with the fields `question` and `answer`.

2025/07/24 00:32:29 INFO dspy.teleprompt.mipro_optimizer_v2: 2: Given the fields `question`, produce the fields `answer`.

2025/07/24 00:32:29 INFO dspy.teleprompt.mipro_optimizer_v2:

2025/07/24 00:32:29 INFO dspy.teleprompt.mipro_optimizer_v2: ==> STEP 3: FINDING OPTIMAL PROMPT PARAMETERS <==
2025/07/24 00:32:29 INFO dspy.teleprompt.mipro_optimizer_v2: We will evaluate the program over a series of trials with different combinations of instructions and few-shot examples to find the optimal combination using Bayesian Optimization.

2025/07/24 00:32:29 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 1 / 20 - Full Evaluation of Default Program ==

Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [01:56<00:00, 11.65s/it]

2025/07/24 00:34:26 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/24 00:34:26 INFO dspy.teleprompt.mipro_optimizer_v2: Default program score: 30.0

/home/eugene/projects/deeplearning.ai/.venv/lib/python3.13/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
2025/07/24 00:34:26 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 2 / 20 =====

🏃 View run eval_full_0 at: http://localhost:5000/#/experiments/1/runs/dbb4d35a583c4d3189c191a72d51876f
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 1.00 / 10 (10.0%): 100%|██████████| 10/10 [02:22<00:00, 14.28s/it]

2025/07/24 00:36:49 INFO dspy.evaluate.evaluate: Average Metric: 1 / 10 (10.0%)
2025/07/24 00:36:49 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 10.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 3', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 0'].
2025/07/24 00:36:49 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0]
2025/07/24 00:36:49 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 30.0
2025/07/24 00:36:49 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 00:36:49 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 3 / 20 =====

🏃 View run eval_full_1 at: http://localhost:5000/#/experiments/1/runs/b1d38e5e78e54f6ab955719ac640fb9d
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [02:54<00:00, 17.44s/it]

2025/07/24 00:39:43 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/24 00:39:43 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2025/07/24 00:39:43 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0]
2025/07/24 00:39:43 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 30.0
2025/07/24 00:39:43 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 00:39:43 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 4 / 20 =====

🏃 View run eval_full_2 at: http://localhost:5000/#/experiments/1/runs/bbe64719c9944f62aa63e9368d3a671c
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 1.00 / 4 (25.0%):  40%|████      | 4/10 [01:51<01:45, 17.51s/it]

2025/07/24 00:41:39 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.

Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [03:01<00:00, 18.18s/it]

2025/07/24 00:42:45 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/24 00:42:45 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 0'].
2025/07/24 00:42:45 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0]
2025/07/24 00:42:45 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 30.0
2025/07/24 00:42:45 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 00:42:45 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 5 / 20 =====

🏃 View run eval_full_3 at: http://localhost:5000/#/experiments/1/runs/70e32f1fc2c84264b2eb4ebd4e2bc995
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [09:57<00:00, 59.77s/it]

2025/07/24 00:52:43 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/24 00:52:43 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far! Score: 40.0
2025/07/24 00:52:43 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/24 00:52:43 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0]
2025/07/24 00:52:43 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 00:52:43 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 00:52:43 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 6 / 20 =====

🏃 View run eval_full_4 at: http://localhost:5000/#/experiments/1/runs/ecabfd413f964c86a84a4662e409219f
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 0.00 / 7 (0.0%):  70%|███████   | 7/10 [02:24<00:25,  8.65s/it]

2025/07/24 00:55:20 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.

Average Metric: 0.00 / 8 (0.0%):  80%|████████  | 8/10 [02:46<00:25, 12.86s/it]

2025/07/24 00:55:51 ERROR dspy.utils.parallelizer: Error for Example({'question': "Which saxophone hit was both covered by Chet Atkins and used as Benny Hill's signature tune?", 'answer': 'Yakety Sax'}) (input_keys={'question'}): Adapter JSONAdapter failed to parse the LM response.

LM Response: {
  "next_thought": "I have successfully identified the saxophone hit that was covered by Chet Atkins and used as Benny Hill's signature tune. It is \"Yakety Sax}

Expected to find output fields in the LM response: [next_thought, next_tool_name, next_tool_args]

Actual output fields parsed from the LM response: [next_thought]

. Set `provide_traceback=True` for traceback.

Average Metric: 0.00 / 9 (0.0%): : 11it [03:40, 20.00s/it]

2025/07/24 00:56:23 INFO dspy.evaluate.evaluate: Average Metric: 0.0 / 10 (0.0%)
2025/07/24 00:56:24 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2025/07/24 00:56:24 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0, 0.0]
2025/07/24 00:56:24 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 00:56:24 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 00:56:24 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 7 / 20 =====

🏃 View run eval_full_5 at: http://localhost:5000/#/experiments/1/runs/3144c2b4882d4bf58aa30a2409a10f48
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [02:16<00:00, 13.65s/it]

2025/07/24 00:58:40 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)

🏃 View run eval_full_6 at: http://localhost:5000/#/experiments/1/runs/619b343256944b37b945490388080470
🧪 View experiment at: http://localhost:5000/#/experiments/1

2025/07/24 00:58:40 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 0'].
2025/07/24 00:58:40 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0, 0.0, 20.0]
2025/07/24 00:58:40 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 00:58:40 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 00:58:40 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 8 / 20 =====

Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [01:29<00:00,  8.95s/it]

2025/07/24 01:00:10 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/24 01:00:10 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/07/24 01:00:10 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0, 0.0, 20.0, 40.0]
2025/07/24 01:00:10 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 01:00:10 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 01:00:10 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 9 / 20 =====

🏃 View run eval_full_7 at: http://localhost:5000/#/experiments/1/runs/dec79ad76e0e428db73f57822b1a1a7b
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [01:12<00:00,  7.29s/it]

2025/07/24 01:01:23 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/24 01:01:23 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 0'].
2025/07/24 01:01:23 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0, 0.0, 20.0, 40.0, 40.0]
2025/07/24 01:01:23 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 01:01:23 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 01:01:23 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 10 / 20 =====

🏃 View run eval_full_8 at: http://localhost:5000/#/experiments/1/runs/52288ce0043e41f7a1cc86a99999a354
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [02:46<00:00, 16.66s/it]

2025/07/24 01:04:10 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/24 01:04:10 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/24 01:04:10 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0, 0.0, 20.0, 40.0, 40.0, 40.0]
2025/07/24 01:04:10 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 01:04:10 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 01:04:10 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 11 / 20 =====

🏃 View run eval_full_9 at: http://localhost:5000/#/experiments/1/runs/d1f8b27cd29c401093f872eeb334bbb2
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [02:06<00:00, 12.61s/it]

2025/07/24 01:06:16 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/24 01:06:16 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 1', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/24 01:06:16 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0, 0.0, 20.0, 40.0, 40.0, 40.0, 30.0]
2025/07/24 01:06:16 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 01:06:16 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 01:06:16 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 12 / 20 =====

🏃 View run eval_full_10 at: http://localhost:5000/#/experiments/1/runs/ab594ef2b786441c81fefab212a0b776
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [01:17<00:00,  7.72s/it]

2025/07/24 01:07:34 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/24 01:07:34 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 4', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/07/24 01:07:34 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0, 0.0, 20.0, 40.0, 40.0, 40.0, 30.0, 40.0]
2025/07/24 01:07:34 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 01:07:34 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 01:07:34 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 13 / 20 =====

🏃 View run eval_full_11 at: http://localhost:5000/#/experiments/1/runs/d73d7498d24a4e4e93c80f52e356ea29
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 0.00 / 10 (0.0%): 100%|██████████| 10/10 [05:47<00:00, 34.77s/it]

2025/07/24 01:13:21 INFO dspy.evaluate.evaluate: Average Metric: 0 / 10 (0.0%)
2025/07/24 01:13:22 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 1'].
2025/07/24 01:13:22 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0, 0.0, 20.0, 40.0, 40.0, 40.0, 30.0, 40.0, 0.0]
2025/07/24 01:13:22 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 01:13:22 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 01:13:22 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 14 / 20 =====

🏃 View run eval_full_12 at: http://localhost:5000/#/experiments/1/runs/080df64792774e91a46f174851788a73
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [01:19<00:00,  7.99s/it]

2025/07/24 01:14:42 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)
2025/07/24 01:14:42 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 1'].
2025/07/24 01:14:42 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0, 0.0, 20.0, 40.0, 40.0, 40.0, 30.0, 40.0, 0.0, 20.0]
2025/07/24 01:14:42 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 01:14:42 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 01:14:42 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 15 / 20 =====

🏃 View run eval_full_13 at: http://localhost:5000/#/experiments/1/runs/a67a008eba90431f875da9f2402794e5
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [01:13<00:00,  7.36s/it]

2025/07/24 01:15:55 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)

🏃 View run eval_full_14 at: http://localhost:5000/#/experiments/1/runs/1f6a494b735943a593354745119f0985
🧪 View experiment at: http://localhost:5000/#/experiments/1

2025/07/24 01:15:56 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 4'].
2025/07/24 01:15:56 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0, 0.0, 20.0, 40.0, 40.0, 40.0, 30.0, 40.0, 0.0, 20.0, 20.0]
2025/07/24 01:15:56 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 01:15:56 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 01:15:56 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 16 / 20 =====

Average Metric: 0.00 / 10 (0.0%): 100%|██████████| 10/10 [02:59<00:00, 17.92s/it]

2025/07/24 01:18:55 INFO dspy.evaluate.evaluate: Average Metric: 0 / 10 (0.0%)
2025/07/24 01:18:55 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 4', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 3'].
2025/07/24 01:18:55 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0, 0.0, 20.0, 40.0, 40.0, 40.0, 30.0, 40.0, 0.0, 20.0, 20.0, 0.0]
2025/07/24 01:18:55 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 01:18:55 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 01:18:55 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 17 / 20 =====

🏃 View run eval_full_15 at: http://localhost:5000/#/experiments/1/runs/c2d7ed7c00ad4813a54bf63a0eb5059b
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [02:09<00:00, 12.95s/it]

2025/07/24 01:21:05 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/24 01:21:05 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/07/24 01:21:05 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0, 0.0, 20.0, 40.0, 40.0, 40.0, 30.0, 40.0, 0.0, 20.0, 20.0, 0.0, 40.0]
2025/07/24 01:21:05 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 01:21:05 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 01:21:05 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 18 / 20 =====

🏃 View run eval_full_16 at: http://localhost:5000/#/experiments/1/runs/c7b9292bc4674a08bd3cd2cc05034e1a
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [02:34<00:00, 15.50s/it]

2025/07/24 01:23:40 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/24 01:23:40 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 3', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 4'].
2025/07/24 01:23:40 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0, 0.0, 20.0, 40.0, 40.0, 40.0, 30.0, 40.0, 0.0, 20.0, 20.0, 0.0, 40.0, 30.0]
2025/07/24 01:23:40 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 01:23:40 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 01:23:40 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 19 / 20 =====

🏃 View run eval_full_17 at: http://localhost:5000/#/experiments/1/runs/85adc4022e2a4efbbbe86082d852bdb4
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 0.00 / 7 (0.0%):  70%|███████   | 7/10 [01:59<00:20,  6.67s/it]

2025/07/24 01:27:20 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.

Average Metric: 1.00 / 10 (10.0%): : 12it [05:54, 29.55s/it]

2025/07/24 01:29:35 INFO dspy.evaluate.evaluate: Average Metric: 1 / 10 (10.0%)
2025/07/24 01:29:35 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 10.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/24 01:29:35 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0, 0.0, 20.0, 40.0, 40.0, 40.0, 30.0, 40.0, 0.0, 20.0, 20.0, 0.0, 40.0, 30.0, 10.0]
2025/07/24 01:29:35 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 01:29:35 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 01:29:35 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 20 / 20 =====

🏃 View run eval_full_18 at: http://localhost:5000/#/experiments/1/runs/5eee99efb9904b92abe96729ee0bb29b
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 5 (40.0%):  50%|█████     | 5/10 [02:30<01:26, 17.37s/it]

2025/07/24 01:34:41 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.

Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [05:56<00:00, 35.61s/it]

2025/07/24 01:35:31 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/24 01:35:31 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/07/24 01:35:31 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0, 0.0, 20.0, 40.0, 40.0, 40.0, 30.0, 40.0, 0.0, 20.0, 20.0, 0.0, 40.0, 30.0, 10.0, 30.0]
2025/07/24 01:35:31 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 01:35:31 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 01:35:31 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 21 / 20 =====

🏃 View run eval_full_19 at: http://localhost:5000/#/experiments/1/runs/0eda52a695f04ece96c9b26eb30c5e6a
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 1.00 / 8 (12.5%):  80%|████████  | 8/10 [02:58<00:34, 17.00s/it]

2025/07/24 01:38:47 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.

Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [11:02<00:00, 66.21s/it]

2025/07/24 01:46:33 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)
2025/07/24 01:46:33 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 1', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 5'].
2025/07/24 01:46:33 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [30.0, 10.0, 30.0, 30.0, 40.0, 0.0, 20.0, 40.0, 40.0, 40.0, 30.0, 40.0, 0.0, 20.0, 20.0, 0.0, 40.0, 30.0, 10.0, 30.0, 20.0]
2025/07/24 01:46:33 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 01:46:33 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 01:46:33 INFO dspy.teleprompt.mipro_optimizer_v2: Returning best identified program with score 40.0!

🏃 View run eval_full_20 at: http://localhost:5000/#/experiments/1/runs/5f6aa0e49d764113b7e4eedc2bc65446
🧪 View experiment at: http://localhost:5000/#/experiments/1

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

🏃 View run grandiose-elk-615 at: http://localhost:5000/#/experiments/1/runs/f977d1c7c55943c7becbe6e5fa9013a9
🧪 View experiment at: http://localhost:5000/#/experiments/1

[Trace(trace_id=0dec25035eb7434e82bc3791c093ab6a), Trace(trace_id=b4f07acbc4a9423c90b644b31f3eb844), Trace(trace_id=48800bf76c3041b392c533efd3e2c692), Trace(trace_id=0e4c07cb8f8b435698ad479cc9a1c2e5), Trace(trace_id=916bba21c2164e769d7d6e3513ef5add), Trace(trace_id=34d0d4562f0546188f10b9e481deeba5), Trace(trace_id=f2d22809c2a643d4a5321f366e9587f0), Trace(trace_id=d1af3e104379432f84fc423f557f87f2), Trace(trace_id=d0bdfd9bf54a428bb8def36d1cd455d9), Trace(trace_id=cf95613e876c4d8dbd3125f1ace763e3)]

In [44]:
evaluator = Evaluate(
    metric=dspy.evaluate.answer_exact_match,
    devset=valset,
    display_table=True,
    display_progress=True,
    num_threads=8,
)

In [45]:
original_score = evaluator(react)
original_score

Average Metric: 29.00 / 100 (29.0%): 100%|██████████| 100/100 [26:35<00:00, 15.95s/it]

2025/07/24 02:13:09 INFO dspy.evaluate.evaluate: Average Metric: 29 / 100 (29.0%)

,question,example_answer,trajectory,reasoning,pred_answer,answer_exact_match
0,"What movie did ""the king of cool"" play in with Bud Ekins as his st...","""The Great Escape""","{'thought_0': 'Okay, I need to find out which movie Steve McQueen ...","Okay, the answer.",The Great Escape.,✔️ [True]
1,whos family had their own reality tv show. Robert Kardashian or Ma...,their family reality television series,"{'thought_0': ""Okay, I need to find out which of Robert Kardashian...",The Wikipedia page for Robert Kardashian states that he appeared o...,Robert Kardashian,
2,Which star in Shadows in Paradise is a Russian ballerina?,Sofya Skya,"{'thought_0': 'Okay, I need to find out which star in Shadows in P...",I have conducted several searches on Wikipedia to determine which ...,I cannot answer this question.,
3,What was the meaning of the name of the man who appointed Amashsai?,comforter,"{'thought_0': 'Okay, the question is about the meaning of the name...",The question asks for the meaning of the name of the man who appoi...,The name Amashsai (or Amashai) was likely derived from the Hebrew ...,
4,"In addition to the Austrian passport, what is needed to gain acces...",national identity card,"{'thought_0': 'Okay, the question is asking about what is needed t...",The question asks what is needed to gain access to 173 countries a...,A Home Office travel document or a Bruneian International Certific...,
...,...,...,...,...,...,...
95,"What date did the American actress and singer-songwriter, known fo...","April 19, 1994","{'thought_0': ""Okay, I need to find the release date of the actres...",I have successfully identified the correct Elisabeth – Elisabeth W...,"September 14, 2010",
96,What animated creatures were the title characters of the film whic...,seals,"{'thought_0': 'Okay, the question is about animated creatures that...",The question asks for the animated creatures that were the title c...,Seals,✔️ [True]
97,The 1925 Saint Mary's Gaels football team represented what private...,Saint Mary's College of California,"{'thought_0': ""Okay, I need to find out which college the 1925 Sai...",The provided Wikipedia entries clearly state that the 1925 Saint M...,Saint Mary's College of California,✔️ [True]
98,Were Dorothy Arzner and Richard Wallace both French film directors?,no,{'thought_0': 'This is a factual question about film directors. I ...,I investigated the biographical information for both Dorothy Arzne...,No.,✔️ [True]
99,Which artist started recording/performing earlier David Donato or ...,Moya Brennan,"{'thought_0': 'Okay, I need to determine which of David Donato or ...",I attempted to use the `search_wikipedia` tool to find the birthda...,Unable to determine which artist started recording/performing earl...,

🏃 View run eval at: http://localhost:5000/#/experiments/1/runs/eabfea999baf4da8956cdb86af4514fe
🧪 View experiment at: http://localhost:5000/#/experiments/1

29.0

[Trace(trace_id=357f2aee1d574442a5fae5435ed1b83e), Trace(trace_id=b632132a3d6b4754a4a38b7debf47a70), Trace(trace_id=5728757af526446f91b4ce0f5cf5a846), Trace(trace_id=27127ba167c44af897cb9313fb5b8154), Trace(trace_id=d9eb2eb7c9fa4e948e2b97448f2b16f6), Trace(trace_id=75a15dc82c134983b8719a446a036aa1), Trace(trace_id=71371148c325492db325734c1481c4f7), Trace(trace_id=caccc19dfe1e4bb19586b425c8508c3f), Trace(trace_id=456ab2bdd50a4bb3af9b165ad9da4c86), Trace(trace_id=53853a389db14f7e864e4ca384fa9dd1)]

In [46]:
optimized_score = evaluator(optimized_react)
optimized_score

Average Metric: 2.00 / 9 (22.2%):   9%|▉         | 9/100 [05:16<45:46, 30.18s/it]

2025/07/24 02:18:34 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.
2025/07/24 02:18:35 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.

Average Metric: 7.00 / 38 (18.4%):  38%|███▊      | 38/100 [22:52<1:38:16, 95.11s/it]

2025/07/24 02:36:06 ERROR dspy.utils.parallelizer: Error for Example({'question': 'What American singer born 1951 does Jim Rooney  have credits for?', 'answer': 'Iris Luella DeMent'}) (input_keys={'question'}): Adapter JSONAdapter failed to parse the LM response.

LM Response: { "_,_ 1_ _ _ _ _ _ __ __ __ __ __ __ __ __ __ __ __ __ _

Expected to find output fields in the LM response: [next_thought, next_tool_name, next_tool_args]

Actual output fields parsed from the LM response: []

. Set `provide_traceback=True` for traceback.

Average Metric: 11.00 / 48 (22.9%):  49%|████▉     | 49/100 [25:35<12:12, 14.36s/it]

2025/07/24 02:45:59 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.

Average Metric: 11.00 / 54 (20.4%):  55%|█████▌    | 55/100 [33:40<21:55, 29.23s/it]

2025/07/24 02:46:58 ERROR dspy.utils.parallelizer: Error for Example({'question': 'How large is this city in North Rhine-Westphalia as compared to other cities in Germany from which the Krupp family comes?', 'answer': 'the ninth-largest'}) (input_keys={'question'}): Adapter JSONAdapter failed to parse the LM response.

LM Response: {" “ “ “ “ “ “ “ “ “ “ “ “ “ “ “ “ “ “ “ “ “ “ “ “ “ “ “ “ “ “ “

Expected to find output fields in the LM response: [next_thought, next_tool_name, next_tool_args]

Actual output fields parsed from the LM response: []

. Set `provide_traceback=True` for traceback.

Average Metric: 11.00 / 54 (20.4%):  56%|█████▌    | 56/100 [33:48<16:49, 22.95s/it]

2025/07/24 02:47:30 ERROR dspy.utils.parallelizer: Error for Example({'question': 'In what army is Mehmetçik slang for a common a common soldier?', 'answer': 'Ottoman Army'}) (input_keys={'question'}): Adapter JSONAdapter failed to parse the LM response.

LM Response: {
    "query": "search_wikipedia"
}

Expected to find output fields in the LM response: [next_thought, next_tool_name, next_tool_args]

Actual output fields parsed from the LM response: []

. Set `provide_traceback=True` for traceback.

Average Metric: 19.00 / 71 (26.8%):  74%|███████▍  | 74/100 [45:42<08:15, 19.07s/it]

2025/07/24 02:59:12 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.

Average Metric: 24.00 / 97 (24.7%): : 103it [1:14:11, 43.22s/it]

2025/07/24 03:27:21 INFO dspy.evaluate.evaluate: Average Metric: 24.0 / 100 (24.0%)

,question,example_answer,trajectory,reasoning,pred_answer,answer_exact_match,answer
0,"What movie did ""the king of cool"" play in with Bud Ekins as his st...","""The Great Escape""",{'thought_0': 'I need to find out which movie Steve McQueen starre...,"Based on my investigation, Steve McQueen starred in the movie ""Bul...",Bullitt,,NaN
1,whos family had their own reality tv show. Robert Kardashian or Ma...,their family reality television series,{'thought_0': 'I need to find out which of Robert Kardashian or Ma...,"Robert Kardashian had his own reality TV show, ""Keeping Up with th...",Robert Kardashian,,NaN
2,Which star in Shadows in Paradise is a Russian ballerina?,Sofya Skya,"{'thought_0': 'I need to identify which character in ""Shadows in P...","Based on my investigation, Sofya Skya plays a role in ""Shadows in ...",Sofya Skya,✔️ [True],NaN
3,What was the meaning of the name of the man who appointed Amashsai?,comforter,{'thought_0': 'I need to find out the meaning behind the name of t...,The Wikipedia search reveals that the name Amashsai (also spelled ...,burdensome,,NaN
4,"In addition to the Austrian passport, what is needed to gain acces...",national identity card,{'thought_0': 'I need to find out what is needed to gain access to...,"Based on the provided information, a British passport (and therefo...",Austrian passport,,NaN
...,...,...,...,...,...,...,...
95,"What date did the American actress and singer-songwriter, known fo...","April 19, 1994",{'thought_0': 'I need to find the release date of the actress know...,I have repeatedly confirmed that Elisabeth Withers released her se...,"September 14, 2010",,NaN
96,What animated creatures were the title characters of the film whic...,seals,"{'thought_0': ""The question refers to a film based on one of Shake...","Based on the extensive Wikipedia search results, the title charact...",puppets,,NaN
97,The 1925 Saint Mary's Gaels football team represented what private...,Saint Mary's College of California,"{'thought_0': ""I need to find out which college the 1925 Saint Mar...",I've analyzed the provided text and identified the key information...,Saint Mary’s College of California,,NaN
98,Were Dorothy Arzner and Richard Wallace both French film directors?,no,{'thought_0': 'I need to find out if Dorothy Arzner and Richard Wa...,The Wikipedia search revealed that Dorothy Arzner was an American ...,no,✔️ [True],NaN
99,Which artist started recording/performing earlier David Donato or ...,Moya Brennan,{'thought_0': 'I need to determine which artist started recording/...,"Okay, after a thorough investigation using Wikipedia searches, I’v...",David Donato,,NaN

🏃 View run eval at: http://localhost:5000/#/experiments/1/runs/f64f82b74ab14b6eaaaedab76e20d635
🧪 View experiment at: http://localhost:5000/#/experiments/1

24.0

[Trace(trace_id=cfff9844a7984e8a8122b2ca6b358bf1), Trace(trace_id=9c597f082f294feda0054e225c27daf6), Trace(trace_id=fa99f3fafdfb4db7893ebafa23aa3fe3), Trace(trace_id=118917bfb4ae480d8508604551f98702), Trace(trace_id=6499be218a614deead94fd4b4a3369f9), Trace(trace_id=e4f16806da294b09b24e8b79e0c097e2), Trace(trace_id=145b840b26ac471b96aeb2d144e9e0a6), Trace(trace_id=9cbe1d365d6f4ccdaca2ed5ddd51f7a0), Trace(trace_id=67dbe3f321fa4661bbd10f772e028337), Trace(trace_id=90a6ff1ea22c411f9a980a5c3336490a)]

### llama3.1:8b

In [47]:
lm = LM(
    "ollama_chat/llama3.1:8b",
    api_base="http://localhost:11434",
    api_key="",
    max_tokens=40960,
    temperature=0.0,
    cache=False,
)
dspy.configure(lm=lm)

In [48]:
react = ReAct("question -> answer", tools=[search_wikipedia])

In [49]:
tp = MIPROv2(
    metric=dspy.evaluate.answer_exact_match,
    auto="light",
    num_threads=8,
)

In [50]:
optimized_react = tp.compile(
    react,
    trainset=trainset[:10],
    valset=valset[:10],
    requires_permission_to_run=False,
)

2025/07/24 03:27:21 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'ff32884fbdd94eeb9336508483637e8a', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current dspy workflow
2025/07/24 03:27:21 INFO dspy.teleprompt.mipro_optimizer_v2:
RUNNING WITH THE FOLLOWING LIGHT AUTO RUN SETTINGS:
num_trials: 20
minibatch: False
num_fewshot_candidates: 6
num_instruct_candidates: 3
valset size: 10

2025/07/24 03:27:21 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 1: BOOTSTRAP FEWSHOT EXAMPLES <==
2025/07/24 03:27:21 INFO dspy.teleprompt.mipro_optimizer_v2: These will be used as few-shot example candidates for our program and for creating instructions.

2025/07/24 03:27:21 INFO dspy.teleprompt.mipro_optimizer_v2: Bootstrapping N=6 sets of demonstrations...

Bootstrapping set 1/6
Bootstrapping set 2/6
Bootstrapping set 3/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

100%|██████████| 10/10 [03:40<00:00, 22.05s/it]

Bootstrapped 3 full traces after 9 examples for up to 1 rounds, amounting to 10 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 4/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

 80%|████████  | 8/10 [03:00<00:45, 22.62s/it]

Bootstrapped 2 full traces after 8 examples for up to 1 rounds, amounting to 8 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 5/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

 10%|█         | 1/10 [00:13<02:02, 13.58s/it]

Bootstrapped 1 full traces after 1 examples for up to 1 rounds, amounting to 1 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 6/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

 50%|█████     | 5/10 [01:37<01:37, 19.56s/it]

Bootstrapped 3 full traces after 5 examples for up to 1 rounds, amounting to 5 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

2025/07/24 03:35:55 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 2: PROPOSE INSTRUCTION CANDIDATES <==
2025/07/24 03:35:55 INFO dspy.teleprompt.mipro_optimizer_v2: We will use the few-shot examples from the previous step, a generated dataset summary, a summary of the program code, and a randomly selected prompting tip to propose instructions.
2025/07/24 03:36:03 INFO dspy.teleprompt.mipro_optimizer_v2:
Proposing N=3 instructions...

2025/07/24 03:38:11 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.
2025/07/24 03:38:43 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 0:

2025/07/24 03:38:43 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the fields `question`, produce the fields `answer`.

You are an Agent. In each episode, you will be given the fields `question` as input. And you can see your past trajectory so far.
Your goal is to use one or more of the supplied tools to collect any necessary information for producing `answer`.

To do this, you will interleave next_thought, next_tool_name, and next_tool_args in each turn, and also when finishing the task.
After each tool call, you receive a resulting observation, which gets appended to your trajectory.

When writing next_thought, you may reason about the current situation and plan for future steps.
When selecting the next_tool_name and its next_tool_args, the tool must be one of:

(1) search_wikipedia. It takes arguments {'query': {'type': 'string'}}.
(2) finish, whose description is <desc>Marks the task as complete. That is, signals that all information for producing the outputs, i.e. `answer`, are now available to be extracted.</desc>. It takes arguments {}.
When providing `next_tool_args`, the value inside the field must be in JSON format

2025/07/24 03:38:43 INFO dspy.teleprompt.mipro_optimizer_v2: 1: To answer the question "Who did Holly Dunn record 'Daddy's Hands' for?", I need to extract this information from Wikipedia.

Next Thought: I need to search for Holly Dunn on Wikipedia and find out who she recorded "Daddy's Hands" for.

Next Tool Name: search_wikipedia

Next Tool Args: {'query': "Holly Dunn Daddy's Hands"}

Observation: [list of observations from the first tool call]

Next Thought: I need to analyze the observations and extract the answer.

Next Tool Name: None (since we don't need any more tools)

Next Tool Args: {}

Observation: [answer]

2025/07/24 03:38:43 INFO dspy.teleprompt.mipro_optimizer_v2: 2: Given the fields `question`, produce the fields `answer`.

You are an Agent. In each episode, you will be given the fields `question` as input. And you can see your past trajectory so far.
Your goal is to use one or more of the supplied tools to collect any necessary information for producing `answer`.

To do this, you will interleave next_thought, next_tool_name, and next_tool_args in each turn, and also when finishing the task.
After each tool call, you receive a resulting observation, which gets appended to your trajectory.

When writing next_thought, you may reason about the current situation and plan for future steps.
When selecting the next_tool_name and its next_tool_args, the tool must be one of:

(1) search_wikipedia. It takes arguments {'query': {'type': 'string'}}.
(2) finish, whose description is <desc>Marks the task as complete. That is, signals that all information for producing the outputs, i.e. `answer`, are now available to be extracted.</desc>. It takes arguments {}.
When providing `next_tool_args`, the value inside the field must be in JSON format

2025/07/24 03:38:43 INFO dspy.teleprompt.mipro_optimizer_v2:

2025/07/24 03:38:43 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 1:

2025/07/24 03:38:43 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the fields `question`, produce the fields `answer`.

2025/07/24 03:38:43 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Given a set of text passages, extract the information about who Holly Dunn recorded "Daddy's Hands" for.

2025/07/24 03:38:43 INFO dspy.teleprompt.mipro_optimizer_v2: 2: Given a text describing who Holly Dunn recorded "Daddy's Hands" for, extract the artist's record label.

2025/07/24 03:38:43 INFO dspy.teleprompt.mipro_optimizer_v2:

2025/07/24 03:38:43 INFO dspy.teleprompt.mipro_optimizer_v2: ==> STEP 3: FINDING OPTIMAL PROMPT PARAMETERS <==
2025/07/24 03:38:43 INFO dspy.teleprompt.mipro_optimizer_v2: We will evaluate the program over a series of trials with different combinations of instructions and few-shot examples to find the optimal combination using Bayesian Optimization.

2025/07/24 03:38:43 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 1 / 20 - Full Evaluation of Default Program ==

Average Metric: 1.00 / 10 (10.0%): 100%|██████████| 10/10 [01:56<00:00, 11.66s/it]

2025/07/24 03:40:40 INFO dspy.evaluate.evaluate: Average Metric: 1 / 10 (10.0%)
2025/07/24 03:40:40 INFO dspy.teleprompt.mipro_optimizer_v2: Default program score: 10.0

/home/eugene/projects/deeplearning.ai/.venv/lib/python3.13/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
2025/07/24 03:40:40 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 2 / 20 =====

🏃 View run eval_full_0 at: http://localhost:5000/#/experiments/1/runs/6d6fb490c71d4190bf11574bfc66d4b4
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [01:39<00:00,  9.91s/it]

2025/07/24 03:42:19 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)

🏃 View run eval_full_1 at: http://localhost:5000/#/experiments/1/runs/42e59727a8d344c185ff259eac06daaf
🧪 View experiment at: http://localhost:5000/#/experiments/1

2025/07/24 03:42:19 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far! Score: 20.0
2025/07/24 03:42:19 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 3', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 0'].
2025/07/24 03:42:19 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0]
2025/07/24 03:42:19 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 03:42:19 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 03:42:19 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 3 / 20 =====

Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [02:40<00:00, 16.06s/it]

2025/07/24 03:45:00 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/24 03:45:00 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far! Score: 40.0
2025/07/24 03:45:00 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2025/07/24 03:45:00 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0]
2025/07/24 03:45:00 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 03:45:00 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 03:45:00 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 4 / 20 =====

🏃 View run eval_full_2 at: http://localhost:5000/#/experiments/1/runs/5a5dc693e83e4f1fbdd49bbd732abf22
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 1.00 / 10 (10.0%): 100%|██████████| 10/10 [03:05<00:00, 18.58s/it]

2025/07/24 03:48:06 INFO dspy.evaluate.evaluate: Average Metric: 1 / 10 (10.0%)
2025/07/24 03:48:06 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 10.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 0'].
2025/07/24 03:48:06 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0]
2025/07/24 03:48:06 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 03:48:06 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 03:48:06 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 5 / 20 =====

🏃 View run eval_full_3 at: http://localhost:5000/#/experiments/1/runs/6ab2805b026442af8902f8c9c45545c9
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [02:50<00:00, 17.03s/it]

2025/07/24 03:50:57 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/24 03:50:57 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/24 03:50:57 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0]
2025/07/24 03:50:57 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 40.0
2025/07/24 03:50:57 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 03:50:57 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 6 / 20 =====

🏃 View run eval_full_4 at: http://localhost:5000/#/experiments/1/runs/f14113df26824bbca45e0b8d061a99d8
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 5.00 / 10 (50.0%): 100%|██████████| 10/10 [03:13<00:00, 19.39s/it]

2025/07/24 03:54:11 INFO dspy.evaluate.evaluate: Average Metric: 5 / 10 (50.0%)
2025/07/24 03:54:11 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far! Score: 50.0
2025/07/24 03:54:11 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 50.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2025/07/24 03:54:11 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0, 50.0]
2025/07/24 03:54:11 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/24 03:54:11 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 03:54:11 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 7 / 20 =====

🏃 View run eval_full_5 at: http://localhost:5000/#/experiments/1/runs/75bfa7a4b79f4611a929ee857753de04
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [02:00<00:00, 12.00s/it]

2025/07/24 03:56:11 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)
2025/07/24 03:56:11 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 0'].
2025/07/24 03:56:11 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0, 50.0, 20.0]
2025/07/24 03:56:11 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/24 03:56:11 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 03:56:11 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 8 / 20 =====

🏃 View run eval_full_6 at: http://localhost:5000/#/experiments/1/runs/832867cc02644c389614b00f0d937a65
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): : 12it [12:33, 62.81s/it]

2025/07/24 04:08:45 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/24 04:08:45 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/07/24 04:08:45 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0, 50.0, 20.0, 30.0]
2025/07/24 04:08:45 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/24 04:08:45 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 04:08:45 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 9 / 20 =====

🏃 View run eval_full_7 at: http://localhost:5000/#/experiments/1/runs/f148bd230f924b8890afd80cfc4631ce
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 0.00 / 1 (0.0%):  10%|█         | 1/10 [01:29<13:25, 89.48s/it]

2025/07/24 04:14:31 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.

Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [08:40<00:00, 52.05s/it]

2025/07/24 04:17:26 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)
2025/07/24 04:17:26 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 0'].
2025/07/24 04:17:26 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0, 50.0, 20.0, 30.0, 20.0]
2025/07/24 04:17:26 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/24 04:17:26 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 04:17:26 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 10 / 20 =====

🏃 View run eval_full_8 at: http://localhost:5000/#/experiments/1/runs/9e07133991a447708a755cc8690388ab
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 1.00 / 10 (10.0%): 100%|██████████| 10/10 [03:57<00:00, 23.79s/it]

2025/07/24 04:21:24 INFO dspy.evaluate.evaluate: Average Metric: 1 / 10 (10.0%)
2025/07/24 04:21:24 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 10.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/24 04:21:24 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0, 50.0, 20.0, 30.0, 20.0, 10.0]
2025/07/24 04:21:24 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/24 04:21:24 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 04:21:24 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 11 / 20 =====

🏃 View run eval_full_9 at: http://localhost:5000/#/experiments/1/runs/6369f4076dde4158a8603f43e06ad628
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [03:35<00:00, 21.52s/it]

2025/07/24 04:24:59 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/24 04:24:59 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 1', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 3'].
2025/07/24 04:24:59 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0, 50.0, 20.0, 30.0, 20.0, 10.0, 30.0]
2025/07/24 04:24:59 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/24 04:24:59 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 04:24:59 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 12 / 20 =====

🏃 View run eval_full_10 at: http://localhost:5000/#/experiments/1/runs/bf70649181274ae0957bb7d6521985ae
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [04:26<00:00, 26.68s/it]

2025/07/24 04:29:26 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/24 04:29:26 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2025/07/24 04:29:26 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0, 50.0, 20.0, 30.0, 20.0, 10.0, 30.0, 30.0]
2025/07/24 04:29:26 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/24 04:29:26 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 04:29:26 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 13 / 20 =====

🏃 View run eval_full_11 at: http://localhost:5000/#/experiments/1/runs/a333f84ca21444bab8a08fae08ce6935
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [04:54<00:00, 29.49s/it]

2025/07/24 04:34:21 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/24 04:34:21 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 4', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2025/07/24 04:34:21 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0, 50.0, 20.0, 30.0, 20.0, 10.0, 30.0, 30.0, 40.0]
2025/07/24 04:34:21 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/24 04:34:21 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 04:34:21 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 14 / 20 =====

🏃 View run eval_full_12 at: http://localhost:5000/#/experiments/1/runs/bbc5a099a1b54a95a6469fb45bafbc81
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [04:13<00:00, 25.34s/it]

2025/07/24 04:38:35 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/24 04:38:35 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 2'].
2025/07/24 04:38:35 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0, 50.0, 20.0, 30.0, 20.0, 10.0, 30.0, 30.0, 40.0, 40.0]
2025/07/24 04:38:35 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/24 04:38:35 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 04:38:35 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 15 / 20 =====

🏃 View run eval_full_13 at: http://localhost:5000/#/experiments/1/runs/81bb5f37ac6e4a79ab0b071daa7f2786
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 1.00 / 9 (11.1%):  90%|█████████ | 9/10 [05:27<00:18, 18.67s/it]

2025/07/24 04:44:49 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.

Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [06:55<00:00, 41.55s/it]

2025/07/24 04:45:31 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)

🏃 View run eval_full_14 at: http://localhost:5000/#/experiments/1/runs/07a1b6bce535496f8fb2f1820c8726ea
🧪 View experiment at: http://localhost:5000/#/experiments/1

2025/07/24 04:45:31 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 1'].
2025/07/24 04:45:31 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0, 50.0, 20.0, 30.0, 20.0, 10.0, 30.0, 30.0, 40.0, 40.0, 20.0]
2025/07/24 04:45:31 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/24 04:45:31 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 04:45:31 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 16 / 20 =====

  0%|          | 0/10 [00:00<?, ?it/s]

2025/07/24 04:46:59 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.

Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [04:36<00:00, 27.64s/it]

2025/07/24 04:50:08 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/24 04:50:08 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/07/24 04:50:08 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0, 50.0, 20.0, 30.0, 20.0, 10.0, 30.0, 30.0, 40.0, 40.0, 20.0, 40.0]
2025/07/24 04:50:08 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/24 04:50:08 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 04:50:08 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 17 / 20 =====

🏃 View run eval_full_15 at: http://localhost:5000/#/experiments/1/runs/9c3693c7c9fe4e739cd4b23db322ae1f
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [02:51<00:00, 17.16s/it]

2025/07/24 04:52:59 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/24 04:52:59 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 3', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 2'].
2025/07/24 04:52:59 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0, 50.0, 20.0, 30.0, 20.0, 10.0, 30.0, 30.0, 40.0, 40.0, 20.0, 40.0, 30.0]
2025/07/24 04:52:59 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 50.0
2025/07/24 04:52:59 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 04:52:59 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 18 / 20 =====

🏃 View run eval_full_16 at: http://localhost:5000/#/experiments/1/runs/6da9231c0f8445e18a3b52a7dbe095a9
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 6.00 / 10 (60.0%): 100%|██████████| 10/10 [21:15<00:00, 127.52s/it]

2025/07/24 05:14:15 INFO dspy.evaluate.evaluate: Average Metric: 6 / 10 (60.0%)
2025/07/24 05:14:15 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far! Score: 60.0
2025/07/24 05:14:15 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 60.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 2'].
2025/07/24 05:14:15 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0, 50.0, 20.0, 30.0, 20.0, 10.0, 30.0, 30.0, 40.0, 40.0, 20.0, 40.0, 30.0, 60.0]
2025/07/24 05:14:15 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/24 05:14:15 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 05:14:15 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 19 / 20 =====

🏃 View run eval_full_17 at: http://localhost:5000/#/experiments/1/runs/bedebe8e6f7a4aaaba5192de924d3882
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [06:21<00:00, 38.11s/it]

2025/07/24 05:20:36 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/24 05:20:36 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 2'].
2025/07/24 05:20:36 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0, 50.0, 20.0, 30.0, 20.0, 10.0, 30.0, 30.0, 40.0, 40.0, 20.0, 40.0, 30.0, 60.0, 30.0]
2025/07/24 05:20:36 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/24 05:20:36 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 05:20:36 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 20 / 20 =====

🏃 View run eval_full_18 at: http://localhost:5000/#/experiments/1/runs/13029a58c374420e81c2c9282bec96ed
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 3.00 / 10 (30.0%): 100%|██████████| 10/10 [05:17<00:00, 31.78s/it]

2025/07/24 05:25:54 INFO dspy.evaluate.evaluate: Average Metric: 3 / 10 (30.0%)
2025/07/24 05:25:54 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 30.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 3'].
2025/07/24 05:25:54 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0, 50.0, 20.0, 30.0, 20.0, 10.0, 30.0, 30.0, 40.0, 40.0, 20.0, 40.0, 30.0, 60.0, 30.0, 30.0]
2025/07/24 05:25:54 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/24 05:25:54 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 05:25:54 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 21 / 20 =====

🏃 View run eval_full_19 at: http://localhost:5000/#/experiments/1/runs/4edb309665874f20b9c0a2c2522ea840
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 4.00 / 10 (40.0%): 100%|██████████| 10/10 [03:34<00:00, 21.50s/it]

2025/07/24 05:29:29 INFO dspy.evaluate.evaluate: Average Metric: 4 / 10 (40.0%)
2025/07/24 05:29:30 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 40.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 1', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 5'].
2025/07/24 05:29:30 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [10.0, 20.0, 40.0, 10.0, 30.0, 50.0, 20.0, 30.0, 20.0, 10.0, 30.0, 30.0, 40.0, 40.0, 20.0, 40.0, 30.0, 60.0, 30.0, 30.0, 40.0]
2025/07/24 05:29:30 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 60.0
2025/07/24 05:29:30 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 05:29:30 INFO dspy.teleprompt.mipro_optimizer_v2: Returning best identified program with score 60.0!

🏃 View run eval_full_20 at: http://localhost:5000/#/experiments/1/runs/a83fe317912744889363e87a778e8d3c
🧪 View experiment at: http://localhost:5000/#/experiments/1

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

🏃 View run flawless-vole-925 at: http://localhost:5000/#/experiments/1/runs/ff32884fbdd94eeb9336508483637e8a
🧪 View experiment at: http://localhost:5000/#/experiments/1

[Trace(trace_id=e9cb32b69e0a43aaadba40aab237d672), Trace(trace_id=1f3ade0a0e7648fa96ee8eaea54140d8), Trace(trace_id=e3b8d7cbcc6d4108beca1e75017e5858), Trace(trace_id=dcb0b08cf5fd4fae99991d02ec6f32f7), Trace(trace_id=b0d65b41e3794246bf248c84a74ba626), Trace(trace_id=4c059314e56a4c16b1368926b3e6140f), Trace(trace_id=0b12c0da8baa4481999fce37a55c091d), Trace(trace_id=344a6a42ad2c46cfbf233f712654012e), Trace(trace_id=c4ab79358f7e43bcaf1783efa6714fb6), Trace(trace_id=4a365a88b4ff4ce69040075526b17818)]

In [51]:
evaluator = Evaluate(
    metric=dspy.evaluate.answer_exact_match,
    devset=valset,
    display_table=True,
    display_progress=True,
    num_threads=8,
)

In [52]:
original_score = evaluator(react)
original_score

Average Metric: 6.00 / 27 (22.2%):  27%|██▋       | 27/100 [05:49<16:00, 13.16s/it]

2025/07/24 05:35:34 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.

Average Metric: 28.00 / 100 (28.0%): 100%|██████████| 100/100 [18:44<00:00, 11.24s/it]

2025/07/24 05:48:14 INFO dspy.evaluate.evaluate: Average Metric: 28 / 100 (28.0%)

,question,example_answer,trajectory,reasoning,pred_answer,answer_exact_match
0,"What movie did ""the king of cool"" play in with Bud Ekins as his st...","""The Great Escape""","{'thought_0': 'I need to find out which movie ""the king of cool"" p...","The question asks about a movie where ""the king of cool"" played in...","I couldn't find a movie where ""the king of cool"" (Steve McQueen) p...",
1,whos family had their own reality tv show. Robert Kardashian or Ma...,their family reality television series,{'thought_0': 'I need to find out which of these two individuals h...,"Based on the information from both Wikipedia articles, it is clear...",Rob Kardashian,
2,Which star in Shadows in Paradise is a Russian ballerina?,Sofya Skya,{'thought_0': 'I need to find information about the movie Shadows ...,The question asks which star in Shadows in Paradise is a Russian b...,Kati Outinen is not a Russian ballerina.,
3,What was the meaning of the name of the man who appointed Amashsai?,comforter,{'thought_0': 'I need to find out who appointed Amashsai. Let me s...,The question asks about the meaning of the name of the man who app...,"The man who appointed Amashsai was Nehemiah, who was the governor ...",
4,"In addition to the Austrian passport, what is needed to gain acces...",national identity card,"{'thought_0': 'To gain access to 173 countries and territories, I ...",The question asks what is needed in addition to an Austrian passpo...,It appears that an Austrian passport is sufficient to gain access ...,
...,...,...,...,...,...,...
95,"What date did the American actress and singer-songwriter, known fo...","April 19, 1994","{'thought_0': ""I need to find information about an American actres...","To find the release date of Katey Sagal's first album, I started b...","April 19, 1994",✔️ [True]
96,What animated creatures were the title characters of the film whic...,seals,{'thought_0': 'We need to identify the play written by William Sha...,The question asks about the title characters of a film based on on...,The title characters of the film are the fairies Oberon and Titani...,
97,The 1925 Saint Mary's Gaels football team represented what private...,Saint Mary's College of California,"{'thought_0': ""I need to find information about the 1925 Saint Mar...","The 1925 Saint Mary's Gaels football team represented a private, c...",Saint Mary's College of California,✔️ [True]
98,Were Dorothy Arzner and Richard Wallace both French film directors?,no,"{'thought_0': ""I need to verify if Dorothy Arzner and Richard Wall...","Based on the observations from Wikipedia searches, Dorothy Arzner ...","No, neither Dorothy Arzner nor Richard Wallace were French film di...",
99,Which artist started recording/performing earlier David Donato or ...,Moya Brennan,{'thought_0': 'To find out which artist started recording/performi...,"To determine which artist started recording/performing earlier, I ...",Moya Brennan,✔️ [True]

🏃 View run eval at: http://localhost:5000/#/experiments/1/runs/7788bea6fddf4c5d95c0db82f7c07b13
🧪 View experiment at: http://localhost:5000/#/experiments/1

28.0

[Trace(trace_id=5ff548d80380486d837d30c98abfeb4a), Trace(trace_id=fafc36305b2748e2adba10f512efde6f), Trace(trace_id=54d4e415f35e423a9b8f8c63086f069e), Trace(trace_id=91c96c841a4049dd913f44555914d8e8), Trace(trace_id=86b3fee6b6dc45698e0f75ff82339e6f), Trace(trace_id=7287b2170ac241afbc20a7ae1440121e), Trace(trace_id=82d1073ae0cb49d0b9257a013b4988cd), Trace(trace_id=3d259b80dd904ff48045bcdd77511a99), Trace(trace_id=6e8fa194cc254965a83631d0cd3bb0a1), Trace(trace_id=f274699ea9eb4fcb86a38a4350bf1d93)]

In [53]:
optimized_score = evaluator(optimized_react)
optimized_score

Average Metric: 43.00 / 100 (43.0%): 100%|██████████| 100/100 [39:50<00:00, 23.91s/it]

2025/07/24 06:28:05 INFO dspy.evaluate.evaluate: Average Metric: 43 / 100 (43.0%)

,question,example_answer,trajectory,reasoning,pred_answer,answer_exact_match
0,"What movie did ""the king of cool"" play in with Bud Ekins as his st...","""The Great Escape""","{'thought_0': 'I need to find out which movie ""the king of cool"" p...","The information about which movie ""the king of cool"" played in wit...",The Great Escape,✔️ [True]
1,whos family had their own reality tv show. Robert Kardashian or Ma...,their family reality television series,{'thought_0': 'I need to find out which family had their own reali...,The information about which family had their own reality TV show c...,Kardashian,
2,Which star in Shadows in Paradise is a Russian ballerina?,Sofya Skya,{'thought_0': 'I need to find out which star in Shadows in Paradis...,The information about which star in Shadows in Paradise is a Russi...,Kati Outinen,
3,What was the meaning of the name of the man who appointed Amashsai?,comforter,"{'thought_0': 'I need to find out who Amashsai was appointed by.',...",The information about who appointed Amashsai can be found in the W...,Nehemiah,
4,"In addition to the Austrian passport, what is needed to gain acces...",national identity card,"{'thought_0': 'To gain access to 173 countries and territories, I ...",To gain access to 173 countries and territories in addition to an ...,Visa-free or visa on arrival status,
...,...,...,...,...,...,...
95,"What date did the American actress and singer-songwriter, known fo...","April 19, 1994",{'thought_0': 'I need to find out what date the American actress a...,The information about Katey Sagal's first album release date can b...,"April 19, 1994",✔️ [True]
96,What animated creatures were the title characters of the film whic...,seals,"{'thought_0': ""I need to find out which animated creatures were th...",The information about which animated creatures were the title char...,Romeo and Juliet (the title characters),
97,The 1925 Saint Mary's Gaels football team represented what private...,Saint Mary's College of California,"{'thought_0': ""I need to find out which private, coeducational col...","The information about which private, coeducational college in Mora...",Saint Mary's College of California,✔️ [True]
98,Were Dorothy Arzner and Richard Wallace both French film directors?,no,{'thought_0': 'I need to find out if Dorothy Arzner and Richard Wa...,The question asks whether Dorothy Arzner and Richard Wallace were ...,We do not have enough information to determine if Dorothy Arzner a...,
99,Which artist started recording/performing earlier David Donato or ...,Moya Brennan,{'thought_0': 'I need to find out which artist started recording/p...,Moya Brennan started recording/performing earlier than David Donat...,Moya Brennan,✔️ [True]

🏃 View run eval at: http://localhost:5000/#/experiments/1/runs/d9d5eae7f0184aa1bc2537bc36a28c27
🧪 View experiment at: http://localhost:5000/#/experiments/1

43.0

[Trace(trace_id=f4d76a7a265b41649a38ff0710cf3930), Trace(trace_id=6ec2bab85f934283a3ce0452a53d3604), Trace(trace_id=7f4e55a28a9b45319aadb8d065a42214), Trace(trace_id=8df0336aa3ab4e4a9c4605f2623337b6), Trace(trace_id=57cc7219f8484919904f9f3e10452bdd), Trace(trace_id=59c8153cbbad473193be5cc38779a3a4), Trace(trace_id=e2e879cc25c041e7ac07936ae46b4746), Trace(trace_id=1d391c529cb24a1bbafefa5e0083f363), Trace(trace_id=5e015e8ecd4e49f8974c4c313f54906e), Trace(trace_id=fdba65a3cb064a38a47cd9569ec81a38)]

### llama3.2:3b

In [55]:
lm = LM(
    "ollama_chat/llama3.2:3b",
    api_base="http://localhost:11434",
    api_key="",
    max_tokens=40960,
    temperature=0.0,
    cache=False,
)
dspy.configure(lm=lm)

In [56]:
react = ReAct("question -> answer", tools=[search_wikipedia])

In [57]:
tp = MIPROv2(
    metric=dspy.evaluate.answer_exact_match,
    auto="light",
    num_threads=8,
)

In [58]:
optimized_react = tp.compile(
    react,
    trainset=trainset[:10],
    valset=valset[:10],
    requires_permission_to_run=False,
)

2025/07/24 09:42:38 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '732f35784d714f04a0da85390cc3620c', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current dspy workflow
2025/07/24 09:42:38 INFO dspy.teleprompt.mipro_optimizer_v2:
RUNNING WITH THE FOLLOWING LIGHT AUTO RUN SETTINGS:
num_trials: 20
minibatch: False
num_fewshot_candidates: 6
num_instruct_candidates: 3
valset size: 10

2025/07/24 09:42:38 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 1: BOOTSTRAP FEWSHOT EXAMPLES <==
2025/07/24 09:42:38 INFO dspy.teleprompt.mipro_optimizer_v2: These will be used as few-shot example candidates for our program and for creating instructions.

2025/07/24 09:42:38 INFO dspy.teleprompt.mipro_optimizer_v2: Bootstrapping N=6 sets of demonstrations...

Bootstrapping set 1/6
Bootstrapping set 2/6
Bootstrapping set 3/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

100%|██████████| 10/10 [01:34<00:00,  9.42s/it]

Bootstrapped 2 full traces after 9 examples for up to 1 rounds, amounting to 10 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 4/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

 80%|████████  | 8/10 [01:09<00:17,  8.68s/it]

Bootstrapped 2 full traces after 8 examples for up to 1 rounds, amounting to 8 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 5/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

 10%|█         | 1/10 [00:09<01:23,  9.27s/it]

Bootstrapped 1 full traces after 1 examples for up to 1 rounds, amounting to 1 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Bootstrapping set 6/6

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

100%|██████████| 10/10 [01:26<00:00,  8.64s/it]

Bootstrapped 2 full traces after 9 examples for up to 1 rounds, amounting to 10 attempts.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

2025/07/24 09:47:00 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 2: PROPOSE INSTRUCTION CANDIDATES <==
2025/07/24 09:47:00 INFO dspy.teleprompt.mipro_optimizer_v2: We will use the few-shot examples from the previous step, a generated dataset summary, a summary of the program code, and a randomly selected prompting tip to propose instructions.
2025/07/24 09:47:04 WARNING dspy.adapters.json_adapter: Failed to use structured output format, falling back to JSON mode.
2025/07/24 09:47:05 INFO dspy.teleprompt.mipro_optimizer_v2:
Proposing N=3 instructions...

2025/07/24 09:48:22 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 0:

2025/07/24 09:48:22 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the fields `question`, produce the fields `answer`.

You are an Agent. In each episode, you will be given the fields `question` as input. And you can see your past trajectory so far.
Your goal is to use one or more of the supplied tools to collect any necessary information for producing `answer`.

To do this, you will interleave next_thought, next_tool_name, and next_tool_args in each turn, and also when finishing the task.
After each tool call, you receive a resulting observation, which gets appended to your trajectory.

When writing next_thought, you may reason about the current situation and plan for future steps.
When selecting the next_tool_name and its next_tool_args, the tool must be one of:

(1) search_wikipedia. It takes arguments {'query': {'type': 'string'}}.
(2) finish, whose description is <desc>Marks the task as complete. That is, signals that all information for producing the outputs, i.e. `answer`, are now available to be extracted.</desc>. It takes arguments {}.
When providing `next_tool_args`, the value inside the field must be in JSON format

2025/07/24 09:48:22 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Given the fields `question` as input, your goal is to use one or more of the supplied tools to collect any necessary information for producing `answer`.

To do this, you will interleave next_thought, next_tool_name, and next_tool_args in each turn, and also when finishing the task.

Firstly, let's examine the given fields. We have `question` as input, which is related to the character who was a lovable-but-goofy mechanic in the TV series "Taxi".

2025/07/24 09:48:22 INFO dspy.teleprompt.mipro_optimizer_v2: 2: Given the question "Who was a lovable-but-goofy mechanic in the TV series 'Taxi'?", produce the answer.

2025/07/24 09:48:22 INFO dspy.teleprompt.mipro_optimizer_v2:

2025/07/24 09:48:22 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 1:

2025/07/24 09:48:22 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the fields `question`, produce the fields `answer`.

2025/07/24 09:48:22 INFO dspy.teleprompt.mipro_optimizer_v2: 1: Given the fields 'question' and 'answer', produce the fields 'answer'.

2025/07/24 09:48:22 INFO dspy.teleprompt.mipro_optimizer_v2: 2: Given the fields `question` and `answer`, produce the fields `[[ ## basic_instruction ## ]]`.

2025/07/24 09:48:22 INFO dspy.teleprompt.mipro_optimizer_v2:

2025/07/24 09:48:22 INFO dspy.teleprompt.mipro_optimizer_v2: ==> STEP 3: FINDING OPTIMAL PROMPT PARAMETERS <==
2025/07/24 09:48:22 INFO dspy.teleprompt.mipro_optimizer_v2: We will evaluate the program over a series of trials with different combinations of instructions and few-shot examples to find the optimal combination using Bayesian Optimization.

2025/07/24 09:48:22 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 1 / 20 - Full Evaluation of Default Program ==

Average Metric: 0.00 / 10 (0.0%): 100%|██████████| 10/10 [01:32<00:00,  9.27s/it]

2025/07/24 09:49:55 INFO dspy.evaluate.evaluate: Average Metric: 0 / 10 (0.0%)
2025/07/24 09:49:55 INFO dspy.teleprompt.mipro_optimizer_v2: Default program score: 0.0

/home/eugene/projects/deeplearning.ai/.venv/lib/python3.13/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
2025/07/24 09:49:55 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 2 / 20 =====

🏃 View run eval_full_0 at: http://localhost:5000/#/experiments/1/runs/299c08350af3459fae6715c687eebfb4
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 0.00 / 10 (0.0%): 100%|██████████| 10/10 [01:40<00:00, 10.10s/it]

2025/07/24 09:51:36 INFO dspy.evaluate.evaluate: Average Metric: 0 / 10 (0.0%)
2025/07/24 09:51:37 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 3', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 0'].
2025/07/24 09:51:37 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0]
2025/07/24 09:51:37 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 0.0
2025/07/24 09:51:37 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 09:51:37 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 3 / 20 =====

🏃 View run eval_full_1 at: http://localhost:5000/#/experiments/1/runs/f29e54d282b84a37bec958ca101c867c
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 1.00 / 10 (10.0%): 100%|██████████| 10/10 [02:05<00:00, 12.56s/it]

2025/07/24 09:53:42 INFO dspy.evaluate.evaluate: Average Metric: 1 / 10 (10.0%)
2025/07/24 09:53:43 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far! Score: 10.0
2025/07/24 09:53:43 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 10.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2025/07/24 09:53:43 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0]
2025/07/24 09:53:43 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 10.0
2025/07/24 09:53:43 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 09:53:43 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 4 / 20 =====

🏃 View run eval_full_2 at: http://localhost:5000/#/experiments/1/runs/060115c8b5e747a2b39658bd2cc72c02
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 0.00 / 10 (0.0%): : 11it [02:31, 13.77s/it]

2025/07/24 09:56:14 INFO dspy.evaluate.evaluate: Average Metric: 0 / 10 (0.0%)

2025/07/24 09:56:14 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 0'].
2025/07/24 09:56:14 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0]
2025/07/24 09:56:14 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 10.0
2025/07/24 09:56:14 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 09:56:14 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 5 / 20 =====

🏃 View run eval_full_3 at: http://localhost:5000/#/experiments/1/runs/3804c2f3cef84aafa8862a657b6e1a4c
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [02:01<00:00, 12.18s/it]

2025/07/24 09:58:16 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)
2025/07/24 09:58:16 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far! Score: 20.0
2025/07/24 09:58:16 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/24 09:58:16 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0]
2025/07/24 09:58:16 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 09:58:16 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 09:58:16 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 6 / 20 =====

🏃 View run eval_full_4 at: http://localhost:5000/#/experiments/1/runs/ca3528036c1c47b997e370142864fbc9
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 0.00 / 10 (0.0%): 100%|██████████| 10/10 [02:00<00:00, 12.08s/it]

2025/07/24 10:00:17 INFO dspy.evaluate.evaluate: Average Metric: 0 / 10 (0.0%)
2025/07/24 10:00:17 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 2'].
2025/07/24 10:00:17 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0, 0.0]
2025/07/24 10:00:17 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 10:00:17 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 10:00:17 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 7 / 20 =====

🏃 View run eval_full_5 at: http://localhost:5000/#/experiments/1/runs/29d3cc93920740998595c3645040f6a5
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 0.00 / 10 (0.0%): 100%|██████████| 10/10 [02:11<00:00, 13.16s/it]

2025/07/24 10:02:29 INFO dspy.evaluate.evaluate: Average Metric: 0 / 10 (0.0%)
2025/07/24 10:02:29 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 0'].
2025/07/24 10:02:29 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0, 0.0, 0.0]
2025/07/24 10:02:29 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 10:02:29 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 10:02:29 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 8 / 20 =====

🏃 View run eval_full_6 at: http://localhost:5000/#/experiments/1/runs/aa0ef05dcbcb4557965313d30edefbac
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [01:41<00:00, 10.16s/it]

2025/07/24 10:04:11 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)
2025/07/24 10:04:11 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/07/24 10:04:11 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0, 0.0, 0.0, 20.0]
2025/07/24 10:04:11 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 10:04:11 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 10:04:11 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 9 / 20 =====

🏃 View run eval_full_7 at: http://localhost:5000/#/experiments/1/runs/22d48dbcc7ef4049acb6e15e57c6f8d6
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 0.00 / 10 (0.0%): 100%|██████████| 10/10 [01:11<00:00,  7.19s/it]

2025/07/24 10:05:23 INFO dspy.evaluate.evaluate: Average Metric: 0 / 10 (0.0%)
2025/07/24 10:05:23 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 0'].
2025/07/24 10:05:23 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0, 0.0, 0.0, 20.0, 0.0]
2025/07/24 10:05:23 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 10:05:23 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2025/07/24 10:05:23 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 10 / 20 =====

🏃 View run eval_full_8 at: http://localhost:5000/#/experiments/1/runs/be632ed979c54f53940ff8ae5bfa0332
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 1.00 / 10 (10.0%): 100%|██████████| 10/10 [01:28<00:00,  8.87s/it]

2025/07/24 10:06:52 INFO dspy.evaluate.evaluate: Average Metric: 1 / 10 (10.0%)
2025/07/24 10:06:52 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 10.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/24 10:06:52 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0, 0.0, 0.0, 20.0, 0.0, 10.0]
2025/07/24 10:06:52 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 10:06:52 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 10:06:52 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 11 / 20 =====

🏃 View run eval_full_9 at: http://localhost:5000/#/experiments/1/runs/cc931ce23d72495f9c47c5fc53aa74bf
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 0.00 / 10 (0.0%): 100%|██████████| 10/10 [01:04<00:00,  6.41s/it]

2025/07/24 10:07:56 INFO dspy.evaluate.evaluate: Average Metric: 0 / 10 (0.0%)
2025/07/24 10:07:57 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 1', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/24 10:07:57 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0, 0.0, 0.0, 20.0, 0.0, 10.0, 0.0]
2025/07/24 10:07:57 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 10:07:57 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 10:07:57 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 12 / 20 =====

🏃 View run eval_full_10 at: http://localhost:5000/#/experiments/1/runs/0cfe90e47c7942d19c06f55e468354c8
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 0.00 / 10 (0.0%): 100%|██████████| 10/10 [01:17<00:00,  7.79s/it]

2025/07/24 10:09:15 INFO dspy.evaluate.evaluate: Average Metric: 0 / 10 (0.0%)
2025/07/24 10:09:15 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 4', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/07/24 10:09:15 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0, 0.0, 0.0, 20.0, 0.0, 10.0, 0.0, 0.0]
2025/07/24 10:09:15 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 10:09:15 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 10:09:15 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 13 / 20 =====

🏃 View run eval_full_11 at: http://localhost:5000/#/experiments/1/runs/b4c7d9dda5fd445094ad0c78eb8cdb5b
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [01:57<00:00, 11.77s/it]

2025/07/24 10:11:13 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)
2025/07/24 10:11:13 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 1'].
2025/07/24 10:11:13 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0, 0.0, 0.0, 20.0, 0.0, 10.0, 0.0, 0.0, 20.0]
2025/07/24 10:11:13 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 10:11:13 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 10:11:13 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 14 / 20 =====

🏃 View run eval_full_12 at: http://localhost:5000/#/experiments/1/runs/ebfdcea1f966419796e22aa30d402ec3
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [02:02<00:00, 12.25s/it]

2025/07/24 10:13:15 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)
2025/07/24 10:13:15 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 1'].
2025/07/24 10:13:15 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0, 0.0, 0.0, 20.0, 0.0, 10.0, 0.0, 0.0, 20.0, 20.0]
2025/07/24 10:13:15 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 10:13:15 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 10:13:15 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 15 / 20 =====

🏃 View run eval_full_13 at: http://localhost:5000/#/experiments/1/runs/2287d8f16e8047e2b7e9163b7e36a402
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 1.00 / 10 (10.0%): 100%|██████████| 10/10 [02:02<00:00, 12.20s/it]

2025/07/24 10:15:18 INFO dspy.evaluate.evaluate: Average Metric: 1 / 10 (10.0%)
2025/07/24 10:15:18 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 10.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 4'].
2025/07/24 10:15:18 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0, 0.0, 0.0, 20.0, 0.0, 10.0, 0.0, 0.0, 20.0, 20.0, 10.0]
2025/07/24 10:15:18 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 10:15:18 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 10:15:18 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 16 / 20 =====

🏃 View run eval_full_14 at: http://localhost:5000/#/experiments/1/runs/0d6eb4e056d04cd0a3b82a0dca5f207b
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 0.00 / 10 (0.0%): 100%|██████████| 10/10 [01:20<00:00,  8.04s/it]

2025/07/24 10:16:38 INFO dspy.evaluate.evaluate: Average Metric: 0 / 10 (0.0%)
2025/07/24 10:16:39 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 4', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 3'].
2025/07/24 10:16:39 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0, 0.0, 0.0, 20.0, 0.0, 10.0, 0.0, 0.0, 20.0, 20.0, 10.0, 0.0]
2025/07/24 10:16:39 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 10:16:39 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 10:16:39 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 17 / 20 =====

🏃 View run eval_full_15 at: http://localhost:5000/#/experiments/1/runs/46ab7325ccbb4b7094f3bedafffa36c2
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [01:58<00:00, 11.89s/it]

2025/07/24 10:18:38 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)

2025/07/24 10:18:38 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 2', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/07/24 10:18:38 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0, 0.0, 0.0, 20.0, 0.0, 10.0, 0.0, 0.0, 20.0, 20.0, 10.0, 0.0, 20.0]
2025/07/24 10:18:38 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 10:18:38 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 10:18:38 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 18 / 20 =====

🏃 View run eval_full_16 at: http://localhost:5000/#/experiments/1/runs/3b408cef38fa49fab0a6ea45aac40ff2
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 1.00 / 10 (10.0%): 100%|██████████| 10/10 [01:45<00:00, 10.55s/it]

2025/07/24 10:20:23 INFO dspy.evaluate.evaluate: Average Metric: 1 / 10 (10.0%)
2025/07/24 10:20:24 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 10.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 3', 'Predictor 1: Instruction 0', 'Predictor 1: Few-Shot Set 4'].
2025/07/24 10:20:24 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0, 0.0, 0.0, 20.0, 0.0, 10.0, 0.0, 0.0, 20.0, 20.0, 10.0, 0.0, 20.0, 10.0]
2025/07/24 10:20:24 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 10:20:24 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 10:20:24 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 19 / 20 =====

🏃 View run eval_full_17 at: http://localhost:5000/#/experiments/1/runs/edd8f1243d8447c18dd9bd81e18892b2
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 2.00 / 10 (20.0%): 100%|██████████| 10/10 [02:08<00:00, 12.88s/it]

2025/07/24 10:22:32 INFO dspy.evaluate.evaluate: Average Metric: 2 / 10 (20.0%)
2025/07/24 10:22:33 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 20.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 4'].
2025/07/24 10:22:33 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0, 0.0, 0.0, 20.0, 0.0, 10.0, 0.0, 0.0, 20.0, 20.0, 10.0, 0.0, 20.0, 10.0, 20.0]
2025/07/24 10:22:33 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 10:22:33 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 10:22:33 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 20 / 20 =====

🏃 View run eval_full_18 at: http://localhost:5000/#/experiments/1/runs/6866c77ee79d47d59c1d5c9de6b50fdb
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 1.00 / 10 (10.0%): 100%|██████████| 10/10 [00:50<00:00,  5.00s/it]

2025/07/24 10:23:23 INFO dspy.evaluate.evaluate: Average Metric: 1 / 10 (10.0%)
2025/07/24 10:23:23 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 10.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 0', 'Predictor 1: Instruction 2', 'Predictor 1: Few-Shot Set 1'].
2025/07/24 10:23:23 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0, 0.0, 0.0, 20.0, 0.0, 10.0, 0.0, 0.0, 20.0, 20.0, 10.0, 0.0, 20.0, 10.0, 20.0, 10.0]
2025/07/24 10:23:23 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 10:23:23 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 10:23:23 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 21 / 20 =====

🏃 View run eval_full_19 at: http://localhost:5000/#/experiments/1/runs/228211b7f20b48e387ab2ab012fd2c6b
🧪 View experiment at: http://localhost:5000/#/experiments/1
Average Metric: 0.00 / 10 (0.0%): 100%|██████████| 10/10 [01:14<00:00,  7.48s/it]

2025/07/24 10:24:38 INFO dspy.evaluate.evaluate: Average Metric: 0 / 10 (0.0%)
2025/07/24 10:24:38 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 1', 'Predictor 1: Instruction 1', 'Predictor 1: Few-Shot Set 5'].
2025/07/24 10:24:38 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [0.0, 0.0, 10.0, 0.0, 20.0, 0.0, 0.0, 20.0, 0.0, 10.0, 0.0, 0.0, 20.0, 20.0, 10.0, 0.0, 20.0, 10.0, 20.0, 10.0, 0.0]
2025/07/24 10:24:38 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 20.0
2025/07/24 10:24:38 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2025/07/24 10:24:38 INFO dspy.teleprompt.mipro_optimizer_v2: Returning best identified program with score 20.0!

🏃 View run eval_full_20 at: http://localhost:5000/#/experiments/1/runs/644839495b4a4eb0a236ecd164939b78
🧪 View experiment at: http://localhost:5000/#/experiments/1

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

🏃 View run casual-owl-302 at: http://localhost:5000/#/experiments/1/runs/732f35784d714f04a0da85390cc3620c
🧪 View experiment at: http://localhost:5000/#/experiments/1

[Trace(trace_id=b96749ae2d8943e78f9a92d3b690a4c4), Trace(trace_id=3b9def2dbf614f7ea5a32026ccf2ff0f), Trace(trace_id=1bd04a0225244409aeed4034cc48648c), Trace(trace_id=281c1e4f8e5b4c2089435333922859f9), Trace(trace_id=e6111aef1a1d42c4bf9c52caf8392a06), Trace(trace_id=0a55821f34c24936aa8f464462273d19), Trace(trace_id=e836dfb48d0e420aba7cf5738deadc45), Trace(trace_id=ae2ccd98acbb42a5bd6accadbc6e4065), Trace(trace_id=b91cd6b6f4ef4a23842806c9e3a1a24b), Trace(trace_id=ee95079dde2d40b791401a12a07e7a12)]

In [59]:
evaluator = Evaluate(
    metric=dspy.evaluate.answer_exact_match,
    devset=valset,
    display_table=True,
    display_progress=True,
    num_threads=8,
)

In [60]:
original_score = evaluator(react)
original_score

Average Metric: 5.00 / 100 (5.0%): 100%|██████████| 100/100 [15:16<00:00,  9.16s/it]

2025/07/24 10:39:55 INFO dspy.evaluate.evaluate: Average Metric: 5 / 100 (5.0%)

,question,example_answer,trajectory,reasoning,pred_answer,answer_exact_match
0,"What movie did ""the king of cool"" play in with Bud Ekins as his st...","""The Great Escape""","{'thought_0': 'The actor who played ""the king of cool"" is Johnny K...","Johnny Knoxville worked with Bud Ekins in several films, but one n...","The movie where Johnny Knoxville played as his stunt double was ""J...",
1,whos family had their own reality tv show. Robert Kardashian or Ma...,their family reality television series,{'thought_0': 'The family of Manvel Gamburyan had their own realit...,Manvel Gamburyan's family had their own reality TV show.,Manvel Gamburyan's family had their own reality TV show.,
2,Which star in Shadows in Paradise is a Russian ballerina?,Sofya Skya,{'thought_0': 'The character Natalia is a Russian ballerina in Sha...,The character Natalia was correctly identified as a Russian baller...,Natalia is a Russian ballerina in Shadows in Paradise.,
3,What was the meaning of the name of the man who appointed Amashsai?,comforter,"{'thought_0': ""The question seems to refer to Amaziah, not Amashsa...","The question refers to Amaziah, not Amashsai. The search results f...",Amaziah was a king of Judah who took the throne at the age of 25 a...,
4,"In addition to the Austrian passport, what is needed to gain acces...",national identity card,{'thought_0': 'Visa requirements for travel to 173 countries and t...,The error occurred because the 'type' argument in the search_wikip...,"To gain access to 173 countries and territories, one needs a visa ...",
...,...,...,...,...,...,...
95,"What date did the American actress and singer-songwriter, known fo...","April 19, 1994",{'thought_0': 'The American actress and singer-songwriter known fo...,The American actress and singer-songwriter known for her role as P...,Florence Henderson's first album release date was not specified in...,
96,What animated creatures were the title characters of the film whic...,seals,"{'thought_0': 'The film is likely ""A Midsummer Night\'s Dream"" sin...","The film is likely ""A Midsummer Night's Dream"" since it is one of ...",The title characters of the film are the four young Athenian lover...,
97,The 1925 Saint Mary's Gaels football team represented what private...,Saint Mary's College of California,"{'thought_0': ""The 1925 Saint Mary's Gaels football team likely re...",The 1925 Saint Mary's Gaels football team likely represented Saint...,Saint Mary's College of California,✔️ [True]
98,Were Dorothy Arzner and Richard Wallace both French film directors?,no,{'thought_0': 'Dorothy Arzner and Richard Wallace were both Americ...,Dorothy Arzner and Richard Wallace were both American film directo...,They were both American film directors.,
99,Which artist started recording/performing earlier David Donato or ...,Moya Brennan,{'thought_0': 'The artist who started recording/performing earlier...,The correct answer can be determined by analyzing the search resul...,Moya Brennan started recording/performing earlier than David Donato.,

🏃 View run eval at: http://localhost:5000/#/experiments/1/runs/9fbf22a8817d498e8b72c8666ebbc68a
🧪 View experiment at: http://localhost:5000/#/experiments/1

5.0

[Trace(trace_id=384dd3e3a5ad4b42b4b278d71e07c0e1), Trace(trace_id=008bec749ae84fabbc72b25ffd2502b9), Trace(trace_id=4da3f62cdb0b436fbe0c70819191b825), Trace(trace_id=f30172430019481bb089b671d7d44d13), Trace(trace_id=fb5919fefeb649d190aa1b119297d151), Trace(trace_id=321df61df0264eac9771a48e02876b98), Trace(trace_id=22194f832e534cc1a10a09cc1ae6f87c), Trace(trace_id=2bf28adb953f4cf89f07bb4f64a9a2d0), Trace(trace_id=d88aa011651647f99eaa36296b48cb90), Trace(trace_id=c11683ca807545a59cf575feee4d4f55)]

In [61]:
optimized_score = evaluator(optimized_react)
optimized_score

Average Metric: 14.00 / 100 (14.0%): 100%|██████████| 100/100 [25:13<00:00, 15.14s/it]

2025/07/24 11:05:09 INFO dspy.evaluate.evaluate: Average Metric: 14 / 100 (14.0%)

,question,example_answer,trajectory,reasoning,pred_answer,answer_exact_match
0,"What movie did ""the king of cool"" play in with Bud Ekins as his st...","""The Great Escape""","{'thought_0': 'Harold Sakata played in ""The King of Cool"" movie wi...","The provided information suggests that ""The King of Cool"" is a nic...",no,
1,whos family had their own reality tv show. Robert Kardashian or Ma...,their family reality television series,"{'thought_0': ""Robert Kardashian's family had their own reality TV...",The Kardashian family had their own reality TV show.,no,
2,Which star in Shadows in Paradise is a Russian ballerina?,Sofya Skya,{'thought_0': 'The star in Shadows in Paradise who is a Russian ba...,"The tool used to search for information is Wikipedia, and it retur...",Natalia Makarova,
3,What was the meaning of the name of the man who appointed Amashsai?,comforter,{'thought_0': 'The name of the man who appointed Amashsai is King ...,The question about the name of the man who appointed Amashsai can ...,King David,
4,"In addition to the Austrian passport, what is needed to gain acces...",national identity card,{'thought_0': 'A valid passport from an International Organization...,A valid passport from an International Organization is needed to g...,no,
...,...,...,...,...,...,...
95,"What date did the American actress and singer-songwriter, known fo...","April 19, 1994","{'thought_0': 'The American actress and singer-songwriter, known f...","The American actress and singer-songwriter, known for her role as ...",no,
96,What animated creatures were the title characters of the film whic...,seals,"{'thought_0': ""The title characters of the film based on Shakespea...",The title characters of the film based on Shakespeare's play are f...,fairies,
97,The 1925 Saint Mary's Gaels football team represented what private...,Saint Mary's College of California,"{'thought_0': ""The 1925 Saint Mary's Gaels football team represent...",The 1925 Saint Mary's Gaels football team represented Saint Mary's...,Saint Mary's College of California,✔️ [True]
98,Were Dorothy Arzner and Richard Wallace both French film directors?,no,"{'thought_0': 'No, Dorothy Arzner was an American film director, w...","Dorothy Arzner was an American film director, while Richard Wallac...",no,✔️ [True]
99,Which artist started recording/performing earlier David Donato or ...,Moya Brennan,{'thought_0': 'Moya Brennan started recording/performing earlier t...,Moya Brennan started recording/performing earlier than David Donat...,yes,

🏃 View run eval at: http://localhost:5000/#/experiments/1/runs/9c00d178a4e94640afe8f88936d04ed7
🧪 View experiment at: http://localhost:5000/#/experiments/1

14.0

[Trace(trace_id=1ae15f338e2a469195944332e1cdf619), Trace(trace_id=4d81f3af174149a99231a2ea3d918fd6), Trace(trace_id=2d76b02553aa40eea9be3afa6c41361f), Trace(trace_id=492bba6658bc4d1fb2a2a4b452302141), Trace(trace_id=de0eb8b24e2044fdaad581fa4ad394b7), Trace(trace_id=568542d739f4474ca71fdfb0639e4f6d), Trace(trace_id=fa53e0a7dc47495593f9f64cfe1f0416), Trace(trace_id=a3bf7e561e8c412382e900feee12a44d), Trace(trace_id=24b7bb5d018a4a7181f2fd7e9418e517), Trace(trace_id=95b6bf7b0ff44c6e822b2ff9bb6900da)]